const fs=require('fs');fs.mkdirSync('tests/artifacts',{recursive:true});
const {chromium}=require('../frontend/node_modules/playwright'),assert=require('assert');
(async()=>{const browser=await chromium.launch({args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote'],headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(10000);const errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));let profile={id:2,firstName:'Ayesha',lastName:'Rahman',role:'Student',isVerified:true,universityEmail:'ayesha_44009@bscse.puc.ac.bd'},saved=[],failCheckout=false,prefs={messages:true,offers:true,orders:true,rentals:true,savedListings:true};let idCounter=30;
const today=new Date().toISOString().slice(0,10),now=new Date().toISOString();
const products=[{id:1,title:'Introduction to Algorithms',description:'A clean textbook for your next semester. Includes all chapters, with a few helpful notes.',price:650,transactionType:'Sell',condition:'Good',status:'Available',sellerId:3,sellerName:'Nabil Hasan',sellerVerified:true,categoryId:1,categoryName:'Books',location:'Library',isNegotiable:true,images:[{id:1,imageUrl:'/test-photo/1',isPrimary:true},{id:2,imageUrl:'/test-photo/2',isPrimary:false}],imageUrl:'/test-photo/1',createdAt:now},{id:2,title:'Scientific Calculator',description:'Rent this useful calculator for an exam or a short course.',price:40,transactionType:'Rent',condition:'Like new',status:'Available',sellerId:3,sellerName:'Nabil Hasan',sellerVerified:true,categoryId:2,categoryName:'Electronics',location:'Main gate',images:[{id:3,imageUrl:'/test-photo/2',isPrimary:true}],imageUrl:'/test-photo/2',createdAt:now},{id:3,title:'Semester Notes Bundle',description:'Core CSE notes ready for the next student.',price:0,transactionType:'Giveaway',condition:'Good',status:'Available',sellerId:4,sellerName:'Farhan Ahmed',sellerVerified:true,categoryId:1,categoryName:'Academic Materials',location:'Canteen',images:[],createdAt:now},{id:4,title:'Everyday Campus Hoodie',description:'Comfortable navy hoodie, good condition.',price:850,transactionType:'Sell',condition:'Good',status:'Available',sellerId:4,sellerName:'Farhan Ahmed',sellerVerified:true,categoryId:4,categoryName:'Clothing',location:'Main gate',images:[],createdAt:now}];
const orders=[{id:7,productId:22,productTitle:'Scientific Calculator',buyerId:2,sellerId:3,buyerName:'Ayesha',sellerName:'Nabil',status:'Rented',transactionType:'Rent',rentalDays:3,rentalStartDate:today,rentalDueAt:new Date(Date.now()+86400000).toISOString(),finalPrice:120,pickupStatus:'Completed',createdAt:now},{id:8,productId:1,productTitle:'Introduction to Algorithms',buyerId:2,sellerId:3,buyerName:'Ayesha',sellerName:'Nabil',status:'Completed',transactionType:'Sell',finalPrice:650,pickupStatus:'Completed',createdAt:now},{id:9,productId:4,productTitle:'Everyday Campus Hoodie',buyerId:4,sellerId:2,buyerName:'Farhan',sellerName:'Ayesha',status:'Pending',transactionType:'Sell',finalPrice:850,pickupStatus:'None',createdAt:now}];
await page.route('**/test-photo/*',async route=>{const n=route.request().url().split('/').pop();await route.fulfill({contentType:'image/svg+xml',body:`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="540"><rect width="640" height="540" fill="${n==='1'?'#e0e9df':'#e6e1ef'}"/><rect x="175" y="65" width="290" height="410" rx="${n==='1'?'8':'28'}" fill="${n==='1'?'#275d4d':'#304558'}"/><rect x="199" y="101" width="242" height="95" rx="5" fill="#d0e2ca"/><text x="320" y="155" font-size="27" font-family="sans-serif" text-anchor="middle" fill="#243b31">${n==='1'?'ALGORITHMS':'240 ÷ 6 = 40'}</text><text x="320" y="370" font-size="18" font-family="sans-serif" text-anchor="middle" fill="#e2ece5">Campus demo photo ${n}</text></svg>`})});
await page.route('**/api/**',async route=>{const req=route.request(),u=new URL(req.url()),path=u.pathname,method=req.method();calls.push({method,path,body:method==='GET'?null:req.postData()});let data=[],status=200;const body=()=>req.postDataJSON();
if(path==='/api/users/profile')data=profile;
else if(path==='/api/discovery/stats')data={activeListings:24,verifiedMembers:42,completedExchanges:18};
else if(path==='/api/notifications')data={unread:1,items:[{id:1,title:'Your campus pickup',message:'The seller accepted your request.',isRead:false,createdAt:now,link:'/orders/7'}]};
else if(path==='/api/users/preferences'){if(method==='PUT')prefs=body();data=prefs;}
else if(path==='/api/products/categories')data=[{id:1,categoryName:'Books'},{id:2,categoryName:'Electronics'},{id:3,categoryName:'Academic Materials'},{id:4,categoryName:'Clothing'},{id:5,categoryName:'Food'},{id:6,categoryName:'Accessories'}];
else if(path==='/api/products'&&method==='POST'){const p={...body(),id:idCounter++,sellerId:2,sellerName:'Ayesha Rahman',images:[]};products.push(p);data={id:p.id};}
else if(path==='/api/products'){let items=products.filter(p=>!u.searchParams.get('type')||p.transactionType===u.searchParams.get('type'));const search=u.searchParams.get('search');if(search)items=items.filter(p=>p.title.toLowerCase().includes(search.toLowerCase()));data={items,total:items.length,page:1,pageSize:12};}
else if(path==='/api/products/mine')data=[{...products[3],sellerId:2}];
else if(/^\/api\/products\/\d+\/related$/.test(path))data=products.filter(p=>p.id!==Number(path.split('/')[3])).slice(0,4);
else if(/^\/api\/products\/\d+$/.test(path)){const p=products.find(p=>p.id===Number(path.split('/').pop()));if(method==='PUT')Object.assign(p,body());data=p;}
else if(path==='/api/wishlist')data=products.filter(p=>saved.includes(p.id)).map(p=>({...p,productId:p.id}));
else if(/^\/api\/wishlist\/\d+$/.test(path)){const id=Number(path.split('/').pop());saved=method==='DELETE'?saved.filter(x=>x!==id):[...new Set([...saved,id])];data={saved:method!=='DELETE'};}
else if(/^\/api\/users\/\d+$/.test(path))data={profile:{id:3,firstName:'Nabil',lastName:'Hasan',isVerified:true,department:'CSE',batch:44},completed:12,sold:8,givenAway:2,listings:products};
else if(/^\/api\/community\/reputation\/\d+$/.test(path))data={id:3,name:'Nabil Hasan',isVerified:true,reviewCount:8,averageRating:4.8,reviews:[]};
else if(path==='/api/transactions/locations')data=[{id:2,locationName:'Library'},{id:3,locationName:'Main gate'},{id:4,locationName:'Canteen'}];
else if(path==='/api/cart/quote')data={items:body().items.map(x=>{const p=products.find(p=>p.id===x.productId);return {...p,unitPrice:p.price,rentalDays:x.rentalDays,rentalStartDate:x.rentalStartDate,total:p.price*(x.rentalDays??1),available:true}})};
else if(path==='/api/cart/checkout'){if(failCheckout){status=409;data={error:'A price changed. Review your cart.'}}else data={orderIds:[101,102],message:'Requests sent. Sellers will confirm availability.'};}
else if(path==='/api/transactions/orders')data=orders;
else if(path.endsWith('/conversation'))data={id:20};
else if(path==='/api/dashboard/student')data={activeListings:3,activeRentals:1,pendingSales:1,pendingPurchases:1,offersToRespond:2,unreadMessages:1,wishlist:saved.length,sold:3,givenAway:2,recentOrders:orders.map(o=>({...o,title:o.productTitle})),pickups:[{id:7,title:'Scientific Calculator',pickupTime:new Date(Date.now()+86400000).toISOString(),pickupStatus:'Proposed'}]};
else if(path==='/api/admin/dashboard')data={users:24,listings:12,activeListings:10,transactions:8,stores:3,wantedPosts:5,activeRentals:2,pendingReports:1,recentActivity:[{id:1,reason:'Duplicate listing report',status:'Resolved',resolutionNote:'Owner contacted'}]};
else if(path==='/api/admin/listings')data=products;
else if(path==='/api/admin/wanted')data=[{id:5,title:'Need lab coat',description:'Looking for a clean lab coat.',budget:250,status:'Open',isHidden:false,userId:3}];
else if(path==='/api/admin/stores')data=[{id:1,title:'Campus Books',description:'Books and notebooks from your classmates.',products:3,ownerId:3,isHidden:false}];
else if(path==='/api/admin/reviews')data=[{id:1,comment:'Friendly seller.',rating:5,reviewerId:2,isHidden:false}];
else if(path==='/api/admin/transactions')data=orders;
else if(path==='/api/moderator/users')data=[profile,...Array.from({length:15},(_,i)=>({...profile,id:i+10,firstName:'Student '+i,role:'Student'}))];
else if(path==='/api/moderator/reports')data=[{id:1,reason:'Duplicate listing',reportedProductId:1,reporterId:2,status:'Pending'}];
else if(path==='/api/admin/lookups/pickup-locations')data=[{id:2,name:'Library'},{id:3,name:'Main gate'},{id:4,name:'Canteen'}];
else if(path==='/api/admin/lookups/categories')data=[{id:1,name:'Books',code:''},{id:2,name:'Electronics',code:''}];
else if(path==='/api/stores')data={items:[{id:1,storeName:'Campus Books',description:'Fresh pages for your next chapter.',ownerName:'Nabil Hasan',ownerId:3,productCount:3}],total:1};
else if(path==='/api/stores/1')data={id:1,storeName:'Campus Books',description:'Fresh pages and useful things, from one student to another.',ownerName:'Nabil Hasan',ownerId:3,reviewCount:8,rating:4.8,products:products.filter(p=>p.transactionType!=='Rent').map(p=>({...p,productId:p.id,quantity:2}))};
else if(path==='/api/stores/mine')data={id:1,storeName:'Campus Books',description:'Campus essentials',ownerId:2};
else if(path==='/api/stores/mine/products')data=products.filter(p=>p.transactionType==='Sell').map(p=>({...p,productId:p.id,quantity:2}));
else if(path==='/api/stores/mine/summary')data={completedSales:3,salesTotal:1900,lowStock:2};
else if(path==='/api/wanted')data={items:[],total:0};
await route.fulfill({status,json:data});});
const goto=async path=>{await page.goto((process.env.BASE_URL||'http://127.0.0.1:5173')+path);await page.waitForTimeout(220)};
const noOverflow=async(name)=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,name);
await goto('/');await page.getByRole('heading',{name:'Good finds. Even better connections.'}).waitFor();await page.screenshot({path:'tests/artifacts/home-guest.png',fullPage:true});assert.equal(await page.getByRole('button',{name:'Pause motion'}).count(),0);await goto('/help');await page.getByText('When do I pay?',{exact:true}).click();await page.getByText('Arrange payment with the seller at pickup after inspecting the item.',{exact:false}).waitFor();console.log('PASS guest hero, help/FAQ');
await page.evaluate(()=>sessionStorage.setItem('premscart-token','mock-token'));await goto('/');await page.locator('.live-discovery .catalog-card').first().waitFor();await page.screenshot({path:'tests/artifacts/home-signed-in.png',fullPage:true});
await goto('/marketplace');await page.getByRole('button',{name:'Save Introduction to Algorithms',exact:true}).first().click();await page.getByRole('button',{name:'Unsave Introduction to Algorithms',exact:true}).first().waitFor();await page.getByRole('button',{name:'Filters',exact:false}).first().click();await page.getByLabel('Minimum price (Tk)',{exact:true}).fill('500');await page.getByLabel('Maximum price (Tk)',{exact:true}).fill('100');await page.getByRole('button',{name:'Show results',exact:true}).click();await page.getByText('Minimum price must be less than or equal to maximum price.').waitFor();await page.getByLabel('Maximum price (Tk)',{exact:true}).fill('900');await page.getByRole('button',{name:'Show results',exact:true}).click();assert(page.url().includes('maxPrice=900'));await page.reload();await page.waitForTimeout(200);assert(await page.getByRole('button',{name:'Maximum: 900',exact:false}).count());console.log('PASS wishlist, filter validation, URL persistence');
await goto('/listings/1');await page.getByRole('button',{name:'Photo 2',exact:true}).click();await page.getByRole('button',{name:'Expand photo 2 of 2'}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Previous photo'}).click();await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('button',{name:'Add to cart',exact:true}).click();await page.getByRole('link',{name:'Cart, 1 items',exact:true}).waitFor();await page.screenshot({path:'tests/artifacts/product-desktop.png',fullPage:true});console.log('PASS gallery thumbnails, expansion, seller card, add to cart');
await goto('/listings/2');await page.getByRole('combobox',{name:/Rental duration/}).selectOption('3');await page.getByRole('button',{name:'Rent now',exact:true}).first().click();await page.getByText('Tk 770',{exact:true}).waitFor();await page.getByRole('combobox',{name:/Rental duration/}).selectOption('5');await page.getByText('Tk 850',{exact:true}).waitFor();failCheckout=true;await page.getByRole('button',{name:'Send purchase requests'}).click();await page.getByRole('alert').filter({hasText:'A price changed'}).waitFor();failCheckout=false;await page.getByRole('button',{name:'Send purchase requests'}).click();await page.getByRole('heading',{name:'Your requests are on their way.'}).waitFor();const checkout=calls.filter(x=>x.path==='/api/cart/checkout').pop();assert(JSON.parse(checkout.body).items.some(x=>x.rentalStartDate&&x.rentalDays===5));console.log('PASS rental dates, quote, checkout failure/success');
await goto('/listings/new');await page.getByLabel('Title',{exact:true}).fill('My clean lab notebook');await page.getByRole('combobox',{name:/Category/}).selectOption('1');await page.getByLabel('Description',{exact:true}).fill('Unused ruled notebook ready for next semester.');await page.getByLabel('Asking price (Tk)',{exact:true}).fill('150');await page.getByRole('combobox',{name:/Campus pickup location/}).selectOption('Library');await page.getByRole('button',{name:'Save text draft'}).click();await page.reload();await page.getByRole('button',{name:'Restore draft'}).click();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'My clean lab notebook');await page.getByRole('button',{name:'Preview listing'}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Publish listing',exact:true}).click();await page.getByRole('heading',{name:'My clean lab notebook',exact:true,level:1}).waitFor();console.log('PASS listing text draft, restore, preview, publish');
await goto('/dashboard/purchases');await page.getByRole('button',{name:'I’m ready to return it',exact:true}).waitFor();assert.equal(await page.getByRole('heading',{name:'Introduction to Algorithms',exact:true}).count(),0);await page.getByRole('button',{name:'Completed & cancelled',exact:true}).click();await page.getByRole('heading',{name:'Introduction to Algorithms',exact:true}).waitFor();await goto('/orders/7');await page.getByRole('list',{name:'Order progress'}).waitFor();await page.screenshot({path:'tests/artifacts/order-desktop.png',fullPage:true});await goto('/dashboard');await page.getByText('1 request to review',{exact:true}).waitFor();await page.screenshot({path:'tests/artifacts/dashboard-desktop.png',fullPage:true});console.log('PASS active/history separation, direct order, progress, dashboard next steps');
await goto('/settings/notifications');await page.getByRole('switch',{name:'Messages New messages from students you’re chatting with.'}).uncheck();await page.getByRole('button',{name:'Save preferences'}).click();assert.equal(prefs.messages,false);await goto('/stores/1');await page.getByLabel('Search this store',{exact:true}).fill('Algorithms');assert.equal(await page.locator('.storefront .catalog-card').count(),1);await page.getByLabel('Search this store',{exact:true}).fill('');await page.screenshot({path:'tests/artifacts/store-desktop.png',fullPage:true});console.log('PASS notification preferences, storefront search');
profile.role='Admin';await goto('/');await page.getByRole('heading',{name:'Your platform, at a glance.'}).waitFor();assert.equal(await page.locator('.dashboard-nav').getByText('My listings',{exact:true}).count(),0);await goto('/admin/users');await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByText('Page 2 of 2',{exact:true}).waitFor();await page.getByRole('button',{name:'Change role',exact:true}).first().click();await page.getByLabel('New role').selectOption('Moderator');await page.getByRole('button',{name:'Confirm change'}).click();assert(calls.some(x=>x.method==='PUT'&&x.path.includes('/role')));await goto('/moderator/reports');await page.getByRole('button',{name:'Review report',exact:true}).click();await page.getByLabel('Decision').selectOption('Hide listing');await page.getByLabel('Reason',{exact:true}).fill('Duplicate listing found in review.');await page.getByRole('button',{name:'Confirm change'}).click();await goto('/admin/rentals');await page.getByText('3 days',{exact:true}).waitFor();await page.screenshot({path:'tests/artifacts/admin-rentals.png',fullPage:true});console.log('PASS admin redirect/sidebar, users paging/role modal, report modal, rental management');
profile.role='Student';for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:844});for(const route of ['/','/marketplace','/listings/1','/listings/2','/listings/new','/cart','/dashboard','/orders/7','/stores/1','/settings/notifications','/dashboard/wishlist','/help']){await goto(route);await noOverflow(`${route} overflow at ${width}`)}profile.role='Admin';for(const route of ['/admin','/admin/users','/admin/rentals','/admin/listings','/moderator/reports']){await goto(route);await noOverflow(`${route} overflow at ${width}`)}profile.role='Student'}console.log('PASS responsive routes at 320/390/768/1440');
await page.setViewportSize({width:390,height:844});await goto('/listings/2');await page.locator('.mobile-purchase-bar').waitFor({state:'visible'});await page.screenshot({path:'tests/artifacts/product-mobile.png',fullPage:true});await goto('/marketplace');await page.getByRole('button',{name:'Filters',exact:false}).first().click();await page.screenshot({path:'tests/artifacts/filters-mobile.png',fullPage:true});await page.keyboard.press('Escape');await page.getByRole('button',{name:'Open navigation'}).click();await page.keyboard.press('Escape');await page.evaluate(()=>localStorage.setItem('theme','dark'));await goto('/');await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.fan-card-inner').first().evaluate(e=>getComputedStyle(e).animationName),'none');await page.screenshot({path:'tests/artifacts/home-dark-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS sticky action, filter drawer, escape, dark/reduced motion, no uncaught errors (mock API)');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
