const fs=require('fs');fs.mkdirSync('tests/artifacts',{recursive:true});
const {chromium}=require('../frontend/node_modules/playwright'),assert=require('assert');
(async()=>{const browser=await chromium.launch({args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote'],headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(10000);const errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));let profile={id:2,firstName:'Ayesha',lastName:'Rahman',role:'Student',isVerified:true,universityEmail:'ayesha_44009@bscse.puc.ac.bd'},saved=[],failCheckout=false,prefs={messages:true,offers:true,orders:true,rentals:true,savedListings:true};let idCounter=30;
const today=new Date().toISOString().slice(0,10),now=new Date().toISOString();
const products=[{id:1,title:'Introduction to Algorithms',description:'A clean textbook for your next semester. Includes all chapters, with a few helpful notes.',price:650,transactionType:'Sell',allowRent:true,rentalPrice:40,condition:'Good',status:'Available',sellerId:3,sellerName:'Nabil Hasan',sellerVerified:true,categoryId:1,categoryName:'Books',location:'Library',isNegotiable:true,images:[{id:1,imageUrl:'/test-photo/1',isPrimary:true},{id:2,imageUrl:'/test-photo/2',isPrimary:false}],imageUrl:'/test-photo/1',createdAt:now},{id:2,title:'Scientific Calculator',description:'Rent this useful calculator for an exam or a short course.',price:40,transactionType:'Rent',condition:'Like new',status:'Available',sellerId:3,sellerName:'Nabil Hasan',sellerVerified:true,categoryId:2,categoryName:'Electronics',location:'Main gate',images:[{id:3,imageUrl:'/test-photo/2',isPrimary:true}],imageUrl:'/test-photo/2',createdAt:now},{id:3,title:'Semester Notes Bundle',description:'Core CSE notes ready for the next student.',price:0,transactionType:'Giveaway',condition:'Good',status:'Available',sellerId:4,sellerName:'Farhan Ahmed',sellerVerified:true,categoryId:1,categoryName:'Academic Materials',location:'Canteen',images:[],createdAt:now},{id:4,title:'Everyday Campus Hoodie',description:'Comfortable navy hoodie, good condition.',price:850,transactionType:'Sell',condition:'Good',status:'Available',sellerId:4,sellerName:'Farhan Ahmed',sellerVerified:true,categoryId:4,categoryName:'Clothing',location:'Main gate',images:[],createdAt:now}];
const orders=[{id:7,productId:2,productTitle:'Scientific Calculator',buyerId:2,sellerId:3,buyerName:'Ayesha',sellerName:'Nabil',status:'Rented',transactionType:'Rent',rentalDays:3,rentalStartDate:today,rentalDueAt:new Date(Date.now()+86400000).toISOString(),finalPrice:120,pickupStatus:'Completed',createdAt:now},{id:8,productId:1,productTitle:'Introduction to Algorithms',buyerId:2,sellerId:3,buyerName:'Ayesha',sellerName:'Nabil',status:'Completed',transactionType:'Sell',finalPrice:650,pickupStatus:'Completed',createdAt:now},{id:9,productId:4,productTitle:'Everyday Campus Hoodie',buyerId:4,sellerId:2,buyerName:'Farhan',sellerName:'Ayesha',status:'Pending',transactionType:'Sell',finalPrice:850,pickupStatus:'None',createdAt:now}];
await page.route('**/test-photo/*',async route=>{const n=route.request().url().split('/').pop();await route.fulfill({contentType:'image/svg+xml',body:`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="540"><rect width="640" height="540" fill="${n==='1'?'#e0e9df':'#e6e1ef'}"/><rect x="175" y="65" width="290" height="410" rx="${n==='1'?'8':'28'}" fill="${n==='1'?'#275d4d':'#304558'}"/><rect x="199" y="101" width="242" height="95" rx="5" fill="#d0e2ca"/><text x="320" y="155" font-size="27" font-family="sans-serif" text-anchor="middle" fill="#243b31">${n==='1'?'ALGORITHMS':'240 ÷ 6 = 40'}</text><text x="320" y="370" font-size="18" font-family="sans-serif" text-anchor="middle" fill="#e2ece5">Campus demo photo ${n}</text></svg>`})});
await page.route('**/api/**',async route=>{const req=route.request(),u=new URL(req.url()),path=u.pathname,method=req.method();calls.push({method,path,body:method==='GET'?null:req.postData()});let data=[],status=200;const body=()=>req.postDataJSON();
if(path==='/api/users/profile'){if(method==='PUT')Object.assign(profile,body());data=profile;}
else if(path==='/api/users/profile/image'){profile.profileImage='/test-photo/1';data={imageUrl:profile.profileImage};}
else if(path==='/api/community/reviews'&&method==='POST'){orders.find(o=>o.id===body().orderId).hasReviewed=true;data={id:99};}
else if(path==='/api/wanted/5/respond'){data={conversationId:20};}
else if(path==='/api/chat/conversations')data=[];
else if(path.includes('/messages'))data={items:[],hasMore:false};
else if(path==='/api/discovery/stats')data={activeListings:24,verifiedMembers:42,completedExchanges:18};
else if(path==='/api/notifications')data={unread:1,items:[{id:1,title:'Your campus pickup',message:'The seller accepted your request.',isRead:false,createdAt:now,link:'/orders/7'}]};
else if(path==='/api/users/preferences'){if(method==='PUT')prefs=body();data=prefs;}
else if(path==='/api/products/categories')data=[{id:1,categoryName:'Books'},{id:2,categoryName:'Electronics'},{id:3,categoryName:'Academic Materials'},{id:4,categoryName:'Clothing'},{id:5,categoryName:'Food'},{id:6,categoryName:'Accessories'}];
else if(path==='/api/products'&&method==='POST'){const p={...body(),id:idCounter++,sellerId:2,sellerName:'Ayesha Rahman',images:[]};products.push(p);data={id:p.id};}
else if(path==='/api/products'){let items=products.filter(p=>!u.searchParams.get('type')||p.transactionType===u.searchParams.get('type'));const search=u.searchParams.get('search');if(search)items=items.filter(p=>p.title.toLowerCase().includes(search.toLowerCase()));data={items,total:items.length,page:1,pageSize:12};}
else if(path==='/api/products/mine')data=[{...products[3],sellerId:2}];
else if(/^\/api\/products\/\d+\/related$/.test(path))data=products.filter(p=>p.id!==Number(path.split('/')[3])).slice(0,4);
else if(/^\/api\/products\/\d+$/.test(path)){const p=products.find(p=>p.id===Number(path.split('/').pop()));if(method==='PUT')Object.assign(p,body());data=p;}
else if(path==='/api/wishlist')data=products.filter(p=>saved.includes(p.id)).map(p=>({...p,productId:p.id}));
else if(/^\/api\/wishlist\/\d+$/.test(path)){const id=Number(path.split('/').pop());saved=method==='DELETE'?saved.filter(x=>x!==id):[...new Set([...saved,id])];data={saved:method!=='DELETE'};}
else if(/^\/api\/users\/\d+$/.test(path))data={profile:{id:3,firstName:'Nabil',lastName:'Hasan',isVerified:true,department:'CSE',batch:44},completed:12,sold:8,givenAway:2,listings:products};
else if(/^\/api\/community\/reputation\/\d+$/.test(path))data={id:3,name:'Nabil Hasan',isVerified:true,reviewCount:8,averageRating:4.8,reviews:[]};
else if(path==='/api/transactions/locations')data=[{id:2,locationName:'Library'},{id:3,locationName:'Main gate'},{id:4,locationName:'Canteen'}];
else if(path==='/api/cart/quote')data={items:body().items.map(x=>{const p=products.find(p=>p.id===x.productId),mode=x.mode||p.transactionType,unit=mode==='Rent'&&p.allowRent?p.rentalPrice:p.price;return {...p,transactionType:mode,unitPrice:unit,rentalDays:x.rentalDays,rentalStartDate:x.rentalStartDate,total:unit*(mode==='Rent'?x.rentalDays:1),available:true}})};
else if(path==='/api/cart/checkout'){for(const x of body().items){const p=products.find(p=>p.id===x.productId);orders.push({id:101,productId:p.id,productTitle:p.title,buyerId:2,sellerId:3,status:'Pending',transactionType:x.mode,finalPrice:120,createdAt:now});}data={orderIds:[101],message:'Requests sent.'};}
else if(path==='/api/transactions/orders')data=orders;
else if(path.endsWith('/conversation'))data={id:20};
else if(path==='/api/dashboard/student')data={activeListings:3,activeRentals:1,pendingSales:1,pendingPurchases:1,offersToRespond:2,unreadMessages:1,wishlist:saved.length,sold:3,givenAway:2,recentOrders:orders.map(o=>({...o,title:o.productTitle})),pickups:[{id:7,title:'Scientific Calculator',pickupTime:new Date(Date.now()+86400000).toISOString(),pickupStatus:'Proposed'}]};
else if(path==='/api/admin/dashboard')data={users:24,listings:12,activeListings:10,transactions:8,stores:3,wantedPosts:5,activeRentals:2,pendingReports:1,recentActivity:[{id:1,reason:'Duplicate listing report',status:'Resolved',resolutionNote:'Owner contacted'}]};
else if(path==='/api/admin/listings')data=products;
else if(path==='/api/admin/wanted')data=[{id:5,title:'Need lab coat',description:'Looking for a clean lab coat.',budget:250,status:'Open',isHidden:false,userId:3}];
else if(path==='/api/admin/stores')data=[{id:1,title:'Campus Books',description:'Books and notebooks from your classmates.',products:3,ownerId:3,isHidden:false}];
else if(path==='/api/admin/reviews')data=[{id:1,comment:'Friendly seller.',rating:5,reviewerId:2,isHidden:false}];
else if(path==='/api/admin/transactions')data=orders;
else if(path==='/api/moderator/users')data=[profile,...Array.from({length:15},(_,i)=>({...profile,id:i+10,firstName:'Student '+i,role:'Student'}))];
else if(path==='/api/moderator/reports')data=[{id:1,reason:'Duplicate listing',reportedProductId:1,reporterId:2,status:'Pending'}];
else if(path==='/api/admin/lookups/pickup-locations')data=[{id:2,name:'Library'},{id:3,name:'Main gate'},{id:4,name:'Canteen'}];
else if(path==='/api/admin/lookups/categories')data=[{id:1,name:'Books',code:''},{id:2,name:'Electronics',code:''}];
else if(path==='/api/stores')data={items:[{id:1,storeName:'Campus Books',description:'Fresh pages for your next chapter.',ownerName:'Nabil Hasan',ownerId:3,productCount:3}],total:1};
else if(path==='/api/stores/1')data={id:1,storeName:'Campus Books',description:'Fresh pages and useful things, from one student to another.',ownerName:'Nabil Hasan',ownerId:3,reviewCount:8,rating:4.8,products:products.filter(p=>p.transactionType!=='Rent').map(p=>({...p,productId:p.id,quantity:2}))};
else if(path==='/api/stores/mine')data={id:1,storeName:'Campus Books',description:'Campus essentials',ownerId:2};
else if(path==='/api/stores/mine/products')data=products.filter(p=>p.transactionType==='Sell').map(p=>({...p,productId:p.id,quantity:2}));
else if(path==='/api/stores/mine/summary')data={completedSales:3,salesTotal:1900,lowStock:2};
else if(path==='/api/wanted')data={items:[{id:5,title:'Need a campus hoodie',description:'Looking for a warm hoodie.',userId:3,userName:'Nabil Hasan',status:'Open',budget:900,createdAt:now}],total:1};
await route.fulfill({status,json:data});});
const goto=async path=>{await page.goto((process.env.UI_URL||'http://127.0.0.1:5173')+path);await page.waitForTimeout(220)};
const noOverflow=async(name)=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,name);

await goto('/');await page.evaluate(()=>sessionStorage.setItem('premscart-token','mock-token'));
await goto('/settings/profile');await page.getByRole('heading',{name:'Your profile',exact:true}).waitFor();await page.getByLabel('First name',{exact:true}).fill('Ayesha Updated');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('heading',{name:'Ayesha Updated Rahman'}).waitFor();
await page.locator('input[type=file]').setInputFiles({name:'avatar.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRcUAAAAASUVORK5CYII=','base64')});await page.getByRole('button',{name:'Save photo',exact:true}).click();await page.locator('.account-identity img').waitFor();await page.locator('.member-avatar img').first().waitFor();await page.screenshot({path:'tests/artifacts/profile-desktop.png',fullPage:true});console.log('PASS profile name save and uploaded avatar in account/header');
await goto('/stores');await page.getByRole('link',{name:'Manage my store',exact:true}).waitFor();console.log('PASS store ownership CTA');
await goto('/listings/new');await page.getByLabel('Title',{exact:true}).fill('Flexible campus kit');await page.getByRole('combobox',{name:/Category/}).selectOption('1');await page.getByLabel('Description',{exact:true}).fill('A useful kit for your next semester.');await page.getByLabel('Asking price (Tk)',{exact:true}).fill('500');await page.getByRole('checkbox',{name:/Also offer/}).check();await page.getByLabel('Daily rental price (Tk)',{exact:true}).fill('25');await page.getByRole('combobox',{name:/Campus pickup location/}).selectOption('Library');await page.getByRole('button',{name:'Preview listing'}).click();await page.getByRole('button',{name:'Publish listing',exact:true}).click();await page.getByRole('heading',{name:'Flexible campus kit',exact:true,level:1}).waitFor();let payload=JSON.parse(calls.find(c=>c.path==='/api/products'&&c.method==='POST').body);assert.equal(payload.allowRent,true);assert.equal(payload.rentalPrice,25);console.log('PASS combined sale/rental listing payload');
await goto('/listings/1');await page.getByRole('button',{name:/Rent.*40/}).click();await page.getByRole('combobox',{name:/Rental duration/}).selectOption('3');await page.screenshot({path:'tests/artifacts/dual-listing.png',fullPage:true});await page.getByRole('button',{name:'Rent now',exact:true}).first().click();await page.getByRole('button',{name:'Send purchase requests'}).click();await page.getByRole('heading',{name:'Your requests are on their way.'}).waitFor();payload=JSON.parse(calls.find(c=>c.path==='/api/cart/checkout').body);assert.equal(payload.items[0].mode,'Rent');assert.equal(payload.items[0].rentalDays,3);await goto('/listings/1');await page.getByText('Request sent',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Rent now',exact:true}).count(),0);console.log('PASS chosen rental checkout and request state after refresh');
await goto('/wanted');await page.getByRole('button',{name:'I have this',exact:true}).click();await page.getByRole('combobox',{name:'Your available listing'}).selectOption('4');await page.screenshot({path:'tests/artifacts/wanted-reply.png',fullPage:true});await page.getByRole('button',{name:'Send listing & open chat'}).click();await page.waitForURL('**/messages/20');assert.equal(JSON.parse(calls.find(c=>c.path==='/api/wanted/5/respond').body).productId,4);console.log('PASS wanted listing response opens existing chat');
await goto('/orders/8');await page.getByRole('button',{name:'Review seller',exact:true}).click();await page.getByRole('dialog').waitFor();assert(page.url().endsWith('/orders/8'));await page.getByLabel('Your review').fill('Friendly student and easy pickup.');await page.screenshot({path:'tests/artifacts/review-dialog.png',fullPage:true});await page.getByRole('button',{name:'Post review',exact:true}).click();await page.getByRole('button',{name:'Review submitted',exact:true}).waitFor();await page.reload();await page.getByRole('button',{name:'Review submitted',exact:true}).waitFor();assert.equal(JSON.parse(calls.find(c=>c.path==='/api/community/reviews'&&c.method==='POST').body).orderId,8);console.log('PASS inline order review and submitted state after reload');
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:844});for(const route of ['/settings/profile','/listings/1','/listings/new','/wanted','/stores','/orders/8']){await goto(route);await noOverflow(`${route} overflow at ${width}`)}}await page.setViewportSize({width:390,height:844});await goto('/settings/profile');await page.screenshot({path:'tests/artifacts/profile-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS responsive layouts at 320/390/768/1440, no uncaught JavaScript errors (mock API)');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
