using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
namespace PremsCart.Api.Data.Migrations;
[DbContext(typeof(PremsCartDbContext)), Migration("20260924000000_Completion")]
public class Completion : Migration {
 protected override void Up(MigrationBuilder m) { m.Sql("""
ALTER TABLE "Users" ADD COLUMN "Status" text NOT NULL DEFAULT 'Active', ADD COLUMN "SuspensionReason" text, ADD COLUMN "TokenVersion" integer NOT NULL DEFAULT 0;
ALTER TABLE "Offers" ADD COLUMN "LastProposerId" integer;
CREATE TABLE "OfferProposals" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "OfferId" integer NOT NULL REFERENCES "Offers"("Id") ON DELETE CASCADE, "AuthorId" integer NOT NULL, "Amount" numeric(12,2) NOT NULL, "CreatedAt" timestamptz NOT NULL);
CREATE INDEX "IX_OfferProposals_OfferId" ON "OfferProposals"("OfferId");
UPDATE "Offers" SET "LastProposerId" = CASE WHEN "Status"='Countered' THEN "SellerId" ELSE "BuyerId" END;
INSERT INTO "OfferProposals" ("OfferId","AuthorId","Amount","CreatedAt") SELECT "Id","LastProposerId","OfferAmount","CreatedAt" FROM "Offers";
CREATE TABLE "PasswordResets" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "UserId" integer NOT NULL, "CodeHash" text NOT NULL, "ExpiresAt" timestamptz NOT NULL, "CreatedAt" timestamptz NOT NULL, "FailedAttempts" integer NOT NULL);
CREATE UNIQUE INDEX "IX_PasswordResets_UserId" ON "PasswordResets"("UserId");
ALTER TABLE "Orders" ADD COLUMN "PickupProposerId" integer, ADD COLUMN "PickupStatus" text NOT NULL DEFAULT 'None', ADD COLUMN "CompletedAt" timestamptz;
UPDATE "Orders" SET "PickupProposerId"="SellerId", "PickupStatus"='Proposed' WHERE "Status"='Pickup scheduled';
UPDATE "Orders" SET "PickupStatus"='Completed' WHERE "Status"='Completed';
ALTER TABLE "Reports" ADD COLUMN "ResolutionAction" text, ADD COLUMN "ReviewId" integer, ADD COLUMN "MessageId" integer, ADD COLUMN "ResolutionNote" text, ADD COLUMN "ModeratorId" integer;
ALTER TABLE "Messages" ADD COLUMN "IsHidden" boolean NOT NULL DEFAULT false;
ALTER TABLE "Reviews" ADD COLUMN "IsHidden" boolean NOT NULL DEFAULT false;
ALTER TABLE "Notifications" ADD COLUMN "Link" text NOT NULL DEFAULT '/dashboard', ADD COLUMN "Type" text NOT NULL DEFAULT 'Activity';
UPDATE "Products" p SET "Status"=CASE WHEN p."TransactionType"='Giveaway' THEN 'GivenAway' ELSE 'Sold' END WHERE p."Status"='Unavailable' AND EXISTS (SELECT 1 FROM "Orders" o WHERE o."ProductId"=p."Id" AND o."Status"='Completed') AND p."TransactionType" IN ('Sell','Giveaway');
"""); }
 protected override void Down(MigrationBuilder m) => throw new NotSupportedException("Restore a database backup to revert this migration.");
}
