CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleName" text NOT NULL UNIQUE
);
CREATE TABLE "Universities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UniversityName" text NOT NULL,
    "EmailDomain" text NOT NULL UNIQUE,
    "Address" text
);
CREATE TABLE "Departments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DepartmentName" text NOT NULL,
    "Code" text NOT NULL UNIQUE
);
CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CategoryName" text NOT NULL UNIQUE,
    "Description" text,
    "Image" text
);
CREATE TABLE "PickupLocations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LocationName" text NOT NULL UNIQUE,
    "Description" text
);
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL UNIQUE,
    "PasswordHash" text NOT NULL,
    "UniversityEmail" text NOT NULL UNIQUE,
    "Batch" integer,
    "Department" text,
    "Program" text,
    "StudentIdLastThreeDigits" text,
    "ProfileImage" text,
    "IsVerified" boolean NOT NULL,
    "RoleId" integer NOT NULL REFERENCES "Roles" ("Id") ON DELETE RESTRICT,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");
CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SellerId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "CategoryId" integer NOT NULL REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Price" numeric(12, 2),
    "TransactionType" text NOT NULL,
    "Condition" text NOT NULL,
    "Status" text NOT NULL,
    "Location" text,
    "IsNegotiable" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "CK_Products_Price" CHECK ("Price" IS NULL OR "Price" >= 0)
);
CREATE INDEX "IX_Products_SellerId" ON "Products" ("SellerId");
CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
CREATE TABLE "ProductImages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProductId" integer NOT NULL REFERENCES "Products" ("Id") ON DELETE CASCADE,
    "ImageUrl" text NOT NULL,
    "IsPrimary" boolean NOT NULL
);
CREATE INDEX "IX_ProductImages_ProductId" ON "ProductImages" ("ProductId");
CREATE TABLE "Wishlist" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "ProductId" integer NOT NULL REFERENCES "Products" ("Id") ON DELETE CASCADE,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "AK_Wishlist_User_Product" UNIQUE ("UserId", "ProductId")
);
CREATE INDEX "IX_Wishlist_ProductId" ON "Wishlist" ("ProductId");
CREATE TABLE "WantedPosts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Budget" numeric(12, 2),
    "CategoryId" integer REFERENCES "Categories" ("Id") ON DELETE SET NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX "IX_WantedPosts_UserId" ON "WantedPosts" ("UserId");
CREATE INDEX "IX_WantedPosts_CategoryId" ON "WantedPosts" ("CategoryId");
CREATE TABLE "Conversations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProductId" integer NOT NULL REFERENCES "Products" ("Id") ON DELETE RESTRICT,
    "BuyerId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "SellerId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "AK_Conversations_Product_Buyer_Seller" UNIQUE ("ProductId", "BuyerId", "SellerId")
);
CREATE INDEX "IX_Conversations_BuyerId" ON "Conversations" ("BuyerId");
CREATE INDEX "IX_Conversations_SellerId" ON "Conversations" ("SellerId");
CREATE TABLE "Messages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ConversationId" integer NOT NULL REFERENCES "Conversations" ("Id") ON DELETE CASCADE,
    "SenderId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "MessageText" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL
);
CREATE INDEX "IX_Messages_ConversationId" ON "Messages" ("ConversationId");
CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");
CREATE TABLE "Offers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProductId" integer NOT NULL REFERENCES "Products" ("Id") ON DELETE RESTRICT,
    "BuyerId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "SellerId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "OfferAmount" numeric(12, 2) NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX "IX_Offers_ProductId" ON "Offers" ("ProductId");
CREATE INDEX "IX_Offers_BuyerId" ON "Offers" ("BuyerId");
CREATE INDEX "IX_Offers_SellerId" ON "Offers" ("SellerId");
CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BuyerId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "SellerId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "ProductId" integer NOT NULL REFERENCES "Products" ("Id") ON DELETE RESTRICT,
    "FinalPrice" numeric(12, 2),
    "PickupLocationId" integer REFERENCES "PickupLocations" ("Id") ON DELETE SET NULL,
    "PickupTime" timestamp with time zone,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX "IX_Orders_BuyerId" ON "Orders" ("BuyerId");
CREATE INDEX "IX_Orders_SellerId" ON "Orders" ("SellerId");
CREATE INDEX "IX_Orders_ProductId" ON "Orders" ("ProductId");
CREATE INDEX "IX_Orders_PickupLocationId" ON "Orders" ("PickupLocationId");
CREATE TABLE "Reviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ReviewerId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "ReviewedUserId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "OrderId" integer NOT NULL REFERENCES "Orders" ("Id") ON DELETE RESTRICT,
    "Rating" integer NOT NULL,
    "Comment" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "CK_Reviews_Rating" CHECK ("Rating" BETWEEN 1 AND 5),
    CONSTRAINT "AK_Reviews_Order_Reviewer" UNIQUE ("OrderId", "ReviewerId")
);
CREATE INDEX "IX_Reviews_ReviewerId" ON "Reviews" ("ReviewerId");
CREATE INDEX "IX_Reviews_ReviewedUserId" ON "Reviews" ("ReviewedUserId");
CREATE TABLE "Stores" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OwnerId" integer NOT NULL UNIQUE REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "StoreName" text NOT NULL,
    "Description" text,
    "Logo" text,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE TABLE "StoreProducts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StoreId" integer NOT NULL REFERENCES "Stores" ("Id") ON DELETE CASCADE,
    "ProductId" integer NOT NULL REFERENCES "Products" ("Id") ON DELETE RESTRICT,
    "Quantity" integer NOT NULL,
    CONSTRAINT "CK_StoreProducts_Quantity" CHECK ("Quantity" >= 0),
    CONSTRAINT "AK_StoreProducts_Store_Product" UNIQUE ("StoreId", "ProductId")
);
CREATE INDEX "IX_StoreProducts_ProductId" ON "StoreProducts" ("ProductId");
CREATE TABLE "Reports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ReporterId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "ReportedProductId" integer REFERENCES "Products" ("Id") ON DELETE RESTRICT,
    "ReportedUserId" integer REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    "Reason" text NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX "IX_Reports_ReporterId" ON "Reports" ("ReporterId");
CREATE INDEX "IX_Reports_ReportedProductId" ON "Reports" ("ReportedProductId");
CREATE INDEX "IX_Reports_ReportedUserId" ON "Reports" ("ReportedUserId");
CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

INSERT INTO "Roles" ("Id", "RoleName") VALUES
  (1, 'Student'), (2, 'Business Seller'), (3, 'Moderator'), (4, 'Admin');
INSERT INTO "Universities" ("Id", "UniversityName", "EmailDomain", "Address")
  VALUES (1, 'Premier University', 'bscse.puc.ac.bd', 'Chattogram');
INSERT INTO "Departments" ("Id", "DepartmentName", "Code")
  VALUES (1, 'Computer Science and Engineering', 'CSE');
INSERT INTO "Categories" ("Id", "CategoryName") VALUES
  (1, 'Books'), (2, 'Electronics'), (3, 'Academic Materials'),
  (4, 'Clothing'), (5, 'Food'), (6, 'Accessories');
INSERT INTO "PickupLocations" ("Id", "LocationName") VALUES
  (1, 'CSE Building'), (2, 'Library'), (3, 'Main Gate'),
  (4, 'Cafeteria'), (5, 'Academic Building');
SELECT setval(pg_get_serial_sequence('"Roles"', 'Id'), 4);
SELECT setval(pg_get_serial_sequence('"Universities"', 'Id'), 1);
SELECT setval(pg_get_serial_sequence('"Departments"', 'Id'), 1);
SELECT setval(pg_get_serial_sequence('"Categories"', 'Id'), 6);
SELECT setval(pg_get_serial_sequence('"PickupLocations"', 'Id'), 5);
