import { useEffect, useRef, useState } from 'react'
import { api } from './api'
import { Skeleton } from './UI'
import { type IconName } from './Icon'
const metricLabels:Record<string,string>={users:'Members',activeListings:'Available items',listings:'All items',transactions:'Orders',stores:'Student stores',wantedPosts:'Student requests',activeRentals:'Active rentals',pendingReports:'Reports waiting'}
const sections:Record<string,{title:string;description:string;icon:IconName}>={
 rentals:{title:'Rental management',description:'Review active rentals, due dates, and returns.',icon:'clock'},
 users:{title:'Users & roles',description:'Review accounts, verification, and access.',icon:'user'},
 listings:{title:'Products & rentals',description:'Edit item details and manage visibility.',icon:'market'},
 wanted:{title:'Student requests',description:'Keep requests useful and relevant.',icon:'wanted'},
 stores:{title:'Student shops',description:'Manage storefront details and visibility.',icon:'store'},
 transactions:{title:'All transactions',description:'Monitor purchases, pickups, and rental returns.',icon:'purchase'},
 reviews:{title:'Reviews',description:'Review feedback and hide inappropriate content.',icon:'star'},
}
type Row=Record<string,any>
export default function AdminWorkspace({path}:{path:string}){
 const kind=path.split('/')[2]||'overview',overview=kind==='overview'
 const [page,setPage]=useState(1),[status,setStatus]=useState('')
 const isTransaction=kind==='transactions'||kind==='rentals'
 useEffect(()=>setPage(1),[status])
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState(''),[reload,setReload]=useState(0),[busy,setBusy]=useState(false)
 const [edit,setEdit]=useState<{row:Row;action:'edit'|'visibility'}|null>(null)
 const dialog=useRef<HTMLDialogElement>(null)
 useEffect(()=>{let active=true;setError('');api(`/api/admin/${overview?'dashboard':kind==='rentals'?'transactions':kind}`).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[kind,reload])
 useEffect(()=>{if(edit)dialog.current?.showModal();else dialog.current?.close()},[edit])
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!edit||busy)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{if(edit.action==='visibility')await api(`/api/admin/content/${kind}/${edit.row.id}/visibility`,'POST',{hidden:!edit.row.isHidden,reason:f.get('reason')});else await api(`/api/admin/content/${kind}/${edit.row.id}`,'PUT',{title:f.get('title'),description:f.get('description'),price:f.get('price')?Number(f.get('price')):null});setNotice('Changes saved.');setEdit(null);setReload(n=>n+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const rows:Row[]=Array.isArray(data)?data.filter(r=>(kind!=='rentals'||r.rentalDays)&&JSON.stringify(r).toLowerCase().includes(filter.toLowerCase())&&(!status||(status==='Hidden'?r.isHidden:status==='Visible'?!r.isHidden:r.status===status))):[]
 const pages=Math.max(1,Math.ceil(rows.length/12)),current=Math.min(page,pages)
 return <section className="page-section admin-workspace"><div className="page-heading"><div><span className="eyebrow">PREMSCART / ADMINISTRATION</span><h1>{overview?'Your platform, at a glance.':sections[kind]?.title}</h1><p>{overview?'A concise overview. Use the admin sidebar for detailed management.':sections[kind]?.description}</p></div></div>
 {!edit&&error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p role="status" className="admin-notice">{notice}</p>}{!data&&!error&&<Skeleton count={3} label="Loading workspace"/>}
 {overview&&data?<><div className="admin-metrics">{Object.entries(data).filter(([,value])=>typeof value==='number').map(([key,value])=><div key={key}><strong>{String(value)}</strong><span>{metricLabels[key]??key.replace(/([A-Z])/g,' $1')}</span></div>)}</div><section className="content-panel admin-activity"><h2>Recent moderation activity</h2>{data.recentActivity?.length?data.recentActivity.map((r:any)=><article key={r.id}><strong>{r.reason}</strong><p>{r.resolutionAction??r.status}{r.resolutionNote?` · ${r.resolutionNote}`:''}</p></article>):<p className="helper-copy">Reviewed reports and moderation actions will appear here.</p>}<a href="/moderator/reports">Open reports →</a></section><p className="admin-notice" style={{marginTop:25}}>Verification confirms access to an allowed university email. <a href="/verification">Read how verification works →</a></p></>:data&&<><div className="management-toolbar"><label className="search-field">Search {sections[kind]?.title.toLowerCase()}<input value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}} placeholder="Search title, status, or ID"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{(isTransaction?['Pending','Accepted','Pickup scheduled','Rented','Return requested','Completed','Cancelled']:['Visible','Hidden']).map(s=><option key={s}>{s}</option>)}</select></label><span className="admin-count">{rows.length} record{rows.length===1?'':'s'}</span></div>{kind==='stores'&&<p className="admin-notice">Hiding a shop also pauses new purchases of its inventory. Existing orders remain accessible to their participants.</p>}{isTransaction&&<p className="admin-notice">Transaction history is retained for accountability. Buyers and sellers confirm handoffs and returns; use reports to handle disputes.</p>}
 <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>{kind==='reviews'?'Review':isTransaction?'Order':'Content'}</th><th>{isTransaction?'Participants':'Details'}</th><th>Status</th><th>{isTransaction?'Rental':'Actions'}</th></tr></thead><tbody>{rows.slice((current-1)*12,current*12).map(r=><tr key={r.id}><td><strong>{r.title||r.comment||`Order #${r.id}`}</strong><small>#{r.id}{r.description?` · ${r.description.slice(0,100)}${r.description.length>100?'…':''}`:''}</small></td><td>{kind==='reviews'?`${r.rating}/5 · reviewer #${r.reviewerId}`:isTransaction?`Buyer #${r.buyerId} · Seller #${r.sellerId}`:kind==='stores'?`${r.products} products · Owner #${r.ownerId}`:kind==='wanted'?`Budget: ${r.budget==null?'Not set':`Tk ${r.budget}`}`:`${r.transactionType} · Tk ${r.price??0}${r.transactionType==='Rent'?'/day':''}`}</td><td><span className="status-badge">{r.isHidden?'Hidden':r.status||'Visible'}</span></td><td>{isTransaction?<><span>{r.rentalDays?`${r.rentalDays} days`:'—'}</span>{r.rentalDueAt&&<small>Due {new Date(r.rentalDueAt).toLocaleString()}</small>}{r.returnedAt&&<small>Returned {new Date(r.returnedAt).toLocaleString()}</small>}</>:<div className="row-actions">{kind!=='reviews'&&<button disabled={busy} onClick={()=>{setError('');setEdit({row:r,action:'edit'})}}>Edit</button>}<button disabled={busy} onClick={()=>{setError('');setEdit({row:r,action:'visibility'})}}>{r.isHidden?'Restore':'Hide'}</button></div>}</td></tr>)}{!rows.length&&<tr><td colSpan={4}>No matching records.</td></tr>}</tbody></table></div><nav className="pagination" aria-label="Admin pages"><button disabled={current===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {current} of {pages}</span><button disabled={current===pages} onClick={()=>setPage(p=>p+1)}>Next</button></nav></>}
 <dialog ref={dialog} className="admin-modal" onCancel={e=>{if(busy)e.preventDefault();else setEdit(null)}} onClose={()=>{if(!busy)setEdit(null)}}>{edit&&<form key={`${edit.row.id}-${edit.action}`} onSubmit={save}><span className="eyebrow">{sections[kind]?.title} / #{edit.row.id}</span><h2>{edit.action==='edit'?'Edit details':edit.row.isHidden?'Restore this content?':'Hide this content?'}</h2>{error&&<p className="form-error" role="alert">{error}</p>}{edit.action==='edit'?<><label>{kind==='stores'?'Shop name':'Title'}<input name="title" required maxLength={120} defaultValue={edit.row.title}/></label><label>Description<textarea name="description" required maxLength={3000} rows={5} defaultValue={edit.row.description}/></label>{kind!=='stores'&&<label>{kind==='wanted'?'Budget (optional)':edit.row.transactionType==='Rent'?'Daily price in Tk':'Price in Tk'}<input name="price" type="number" min="0" max="9999999999" step="5" inputMode="numeric" required={kind==='listings'&&edit.row.transactionType!=='Giveaway'} readOnly={edit.row.transactionType==='Giveaway'} defaultValue={edit.row.price??edit.row.budget??''}/></label>}</>:<><p>Content stays in the platform’s records. The owner receives your reason.</p><label>Reason<textarea name="reason" required maxLength={1000} rows={4}/></label></>}<div className="modal-actions"><button type="button" disabled={busy} onClick={()=>setEdit(null)}>Cancel</button><button className="button button-primary" disabled={busy}>{busy?'Saving…':'Save changes'}</button></div></form>}</dialog>
 </section>
}
