import { BusyLabel } from './Loader'
import { requestsChanged } from './RequestState'
import { useEffect, useState } from 'react'
import { api } from './api'
import { readCart, useCart, writeCart } from './cart'
import { PrivateImage } from './Marketplace'
import Icon from './Icon'
import { RentalDates, today } from './rental'
import { Skeleton, SafetyNote, toast } from './UI'
type Quote={id:number;title:string;transactionType?:string;sellerName?:string;location?:string;unitPrice?:number;rentalDays?:number;rentalStartDate?:string;total?:number;imageUrl?:string;available:boolean;error?:string}
export default function Cart({userId,token}:{userId:number;token:string}) {
 const items=useCart(userId), [quote,setQuote]=useState<Quote[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[version,setVersion]=useState(0)
 const signature=JSON.stringify(items)
 useEffect(()=>{let active=true;setQuote([]);if(!items.length){setLoading(false);return}setLoading(true);api<{items:Quote[]}>('/api/cart/quote','POST',{items}).then(r=>{if(active)setQuote(r.items)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[signature,version])
 const total=quote.reduce((sum,x)=>sum+(x.available?x.total??0:0),0)
 function change(id:number,days:number,start:string){try{writeCart(userId,readCart(userId).map(x=>x.productId===id?{...x,productId:id,rentalDays:days,rentalStartDate:start}:x))}catch{setError('Your browser could not save the cart. Check storage settings.')}}
 function remove(id:number){try{writeCart(userId,readCart(userId).filter(x=>x.productId!==id))}catch{setError('Your browser could not update the cart.')}}
 async function checkout(){if(busy)return;setBusy(true);setError('');try{const result=await api('/api/cart/checkout','POST',{items:quote.map(x=>({productId:x.id,mode:x.transactionType,rentalDays:x.transactionType==='Rent'?x.rentalDays:null,rentalStartDate:x.transactionType==='Rent'?(x.rentalStartDate??today()):null,expectedUnitPrice:x.unitPrice}))});writeCart(userId,readCart(userId).filter(x=>!quote.some(q=>q.id===x.productId)));setSuccess(result.message);requestsChanged();toast('Your item requests have been sent.')}catch(e){setError((e as Error).message);setVersion(v=>v+1)}finally{setBusy(false)}}
 return <section className="page-section cart-page"><div className="page-heading"><div><span className="eyebrow">CART</span><h1>Your cart<span className="cart-title-count">{items.length}</span></h1><p>Review your items and rental dates before sending requests to sellers.</p></div><a className="inline-link" href="/marketplace">Continue exploring <Icon name="arrow"/></a></div>
 {error&&<p className="form-error" role="alert">{error}</p>}{success&&<div className="checkout-success" role="status"><span className="success-icon"><Icon name="check"/></span><h2>Your requests are on their way.</h2><p>{success}</p><a className="button button-primary" href="/dashboard/purchases">Track my orders <Icon name="arrow"/></a></div>}
 {!items.length&&!success?<div className="cart-empty"><Icon name="purchase"/><h2>Your cart is empty.</h2><p>Add an item from Shop. Items are not reserved until the seller accepts your request.</p><a className="button button-primary" href="/marketplace">Browse Shop <Icon name="arrow"/></a></div>:items.length>0&&<div className="cart-layout"><div className="cart-items" aria-busy={loading}>{loading?<Skeleton count={2} label="Checking prices and availability"/>:quote.map(p=><article className={`cart-item ${!p.available?'unavailable':''}`} key={p.id}><a className="cart-photo" href={`/listings/${p.id}`}><PrivateImage url={p.imageUrl} token={token} alt={p.title}/></a><div className="cart-item-info"><span className="type-pill">{p.transactionType??'Unavailable'}</span><h2><a href={`/listings/${p.id}`}>{p.title}</a></h2><p>{p.sellerName} {p.location&&`· ${p.location}`}</p>{p.transactionType==='Rent'&&<><RentalDates start={p.rentalStartDate??today()} days={p.rentalDays??1} onChange={(s,d)=>change(p.id,d,s)} disabled={busy}/><small>{p.unitPrice?.toLocaleString()} Tk per day. Your rental starts at pickup.</small></>}{p.error&&<p className="form-error">{p.error}</p>}<button className="text-button" disabled={busy} onClick={()=>remove(p.id)}>Remove</button></div><strong className="cart-price">{p.transactionType==='Giveaway'?'Giveaway':`Tk ${(p.total??0).toLocaleString()}`}</strong></article>)}<p className="cart-local-note"><Icon name="lock"/> Your cart is saved to this browser. Items are reserved after the seller accepts.</p></div><aside className="checkout-summary"><span className="eyebrow">REQUEST SUMMARY</span><h2>Review requests</h2><div><span>Items</span><strong>{quote.length}</strong></div><div><span>Campus pickup</span><strong>No delivery fee</strong></div><div className="cart-total"><span>Total</span><strong>Tk {total.toLocaleString()}</strong></div><p>Pay directly at pickup. Each seller confirms their own request. Rental totals cover your selected number of days.</p><button className="button button-primary" onClick={checkout} disabled={busy||loading||quote.length!==items.length||quote.some(p=>!p.available)}><BusyLabel busy={busy}>{busy?'Sending requests…':'Send requests'}</BusyLabel><Icon name="arrow"/></button><button className="text-button" disabled={busy||loading} onClick={()=>setVersion(v=>v+1)}>Refresh availability</button></aside></div>}
 <SafetyNote/></section>
}
