import { useProductRequest } from './RequestState'
import { useEffect, useState } from 'react'
import { api } from './api'
import { PrivateImage } from './Media'
import Icon from './Icon'
import { toast } from './UI'
export type Product={allowRent?:boolean;rentalPrice?:number|null;id:number;title:string;description?:string;price:number|null;transactionType:string;condition?:string;status:string;location?:string|null;sellerId?:number;sellerName?:string;categoryName?:string;categoryId?:number;isNegotiable?:boolean;isHidden?:boolean;imageUrl?:string|null;storeId?:number|null;createdAt?:string;sellerVerified?:boolean;sellerRating?:number|null;sellerReviewCount?:number;images?:{id:number;imageUrl:string;isPrimary:boolean}[]}
export const money=(amount?:number|null)=>amount==null?'Price unavailable':`Tk ${amount.toLocaleString(undefined,{maximumFractionDigits:0})}`
export const priceLabel=(p:Pick<Product,'transactionType'|'price'>)=>p.transactionType==='Giveaway'?'Giveaway':`${money(p.price)}${p.transactionType==='Rent'?' / day':''}`
export const purchaseLabel=(p:Pick<Product,'transactionType'>)=>p.transactionType==='Rent'?'Review rental':p.transactionType==='Giveaway'?'Review giveaway request':'Review purchase'
export function useWishlist(){const [saved,setSaved]=useState<number[]>([]),[pending,setPending]=useState<number[]>([]);useEffect(()=>{let active=true;const load=()=>api<{productId:number}[]>('/api/wishlist').then(rows=>{if(active)setSaved(rows.map(r=>r.productId))}).catch(()=>{});void load();window.addEventListener('premscart-wishlist-change',load);return()=>{active=false;window.removeEventListener('premscart-wishlist-change',load)}},[]);async function toggle(id:number){if(pending.includes(id))return;setPending(x=>[...x,id]);try{const exists=saved.includes(id);await api(`/api/wishlist/${id}`,exists?'DELETE':'POST');setSaved(x=>exists?x.filter(v=>v!==id):[...x,id]);toast(exists?'Removed from saved items.':'Saved for later.');window.dispatchEvent(new Event('premscart-wishlist-change'))}catch(e){toast((e as Error).message,'error')}finally{setPending(x=>x.filter(v=>v!==id))}}return {saved,pending,toggle}}
export function ProductCard({product:p,token,saved,onSave,disabled=false}:{product:Product;token:string;saved?:boolean;onSave?:()=>void;disabled?:boolean}){const request=useProductRequest(p.id);return <article className="catalog-card"><div className="catalog-photo"><a href={`/listings/${p.id}`} aria-label={`View ${p.title}`}><PrivateImage url={p.imageUrl??p.images?.[0]?.imageUrl} token={token} alt={p.title}/></a><span className={`listing-badge ${p.transactionType.toLowerCase()}`}>{p.allowRent?'Buy or rent':p.transactionType==='Sell'?'For sale':p.transactionType==='Rent'?'For rent':'Giveaway'}</span>{onSave&&<button className={`save-heart ${saved?'is-saved':''}`} aria-label={`${saved?'Unsave':'Save'} ${p.title}`} aria-pressed={!!saved} disabled={disabled} onClick={onSave}><Icon name="heart"/></button>}</div><div className="catalog-body"><small>{p.categoryName??'Campus item'}{p.condition&&` · ${p.condition}`}</small><h3><a href={`/listings/${p.id}`}>{p.title}</a></h3><strong>{priceLabel(p)}</strong>{p.allowRent&&<small className="rental-alternative">or {money(p.rentalPrice)} / day</small>}<p><Icon name="package"/>{p.location??'Campus pickup'}</p>{p.sellerName&&<small className="card-seller">{p.sellerVerified&&<Icon name="shield"/>}{p.sellerName}</small>}<a className="button button-secondary catalog-cta" href={request?.href??`/listings/${p.id}`}>{request?.label??(p.status!=='Available'?p.status:'View item')}<Icon name="arrow"/></a></div></article>}
const recentKey=(id:number)=>`premscart-recent-${id}`
export function rememberProduct(userId:number,id:number){try{const raw=JSON.parse(localStorage.getItem(recentKey(userId))??'[]');const ids=(Array.isArray(raw)?raw:[]).filter((n:unknown)=>Number.isInteger(n)&&n!==id);localStorage.setItem(recentKey(userId),JSON.stringify([id,...ids].slice(0,8)))}catch{/* Browsing works when storage is disabled. */}}
export function RecentProducts({userId,token,exclude}:{userId:number;token:string;exclude?:number}){const [items,setItems]=useState<Product[]>([]);useEffect(()=>{let active=true;try{const raw=JSON.parse(localStorage.getItem(recentKey(userId))??'[]');const ids=(Array.isArray(raw)?raw:[]).filter((id:unknown)=>Number.isInteger(id)&&id!==exclude).slice(0,4);Promise.allSettled(ids.map((id:number)=>api<Product>(`/api/products/${id}`))).then(rows=>{if(active)setItems(rows.flatMap(r=>r.status==='fulfilled'?[r.value]:[]))})}catch{}return()=>{active=false}},[userId,exclude]);if(!items.length)return null;return <section className="recent-section"><div className="panel-heading"><div><span className="eyebrow">PICK UP WHERE YOU LEFT OFF</span><h2>Recently viewed</h2></div><button className="text-button" onClick={()=>{try{localStorage.removeItem(recentKey(userId))}catch{}setItems([])}}>Clear history</button></div><div className="catalog-grid">{items.map(p=><ProductCard key={p.id} product={p} token={token}/>)}</div><p className="helper-copy">Saved only in this browser for your account.</p></section>}
