import Icon from './Icon'
export default function Help(){return <section className="page-section help-page"><span className="eyebrow">A LITTLE GUIDANCE</span><h1>Good exchanges start here.</h1><p className="help-intro">PremsCart connects Premier University students through buying, renting, and giving useful things a new home.</p><div className="help-guides">{[
 ['market','Buy something','Open a listing, choose Buy now or Add to cart, then send your request. Once the seller accepts, agree on a pickup. Payment is arranged directly between you.'],
 ['clock','Rent something','Choose your preferred pickup/return dates and duration. The owner reserves the item after accepting. Your paid rental duration starts when you confirm the actual pickup; the displayed due time is authoritative. Ask the owner in chat if your plans change.'],
 ['gift','Give something away','Post a Giveaway at no charge. Choose a recipient from the requests, arrange pickup, and complete the handoff.'],
 ['shield','Meet with confidence','Use Main gate, Canteen, or Library. Choose a busy time, keep arrangements in chat, inspect the item, and confirm pickup only after you receive it. Never share passwords or verification codes.'],
 ].map(([icon,title,text])=><article key={title}><Icon name={icon as 'market'|'clock'|'gift'|'shield'}/><h2>{title}</h2><p>{text}</p></article>)}</div><section className="faq-section"><h2>A few common questions</h2>{[
 ['Does “verified” mean enrolled?','The badge confirms access to an allowed university email address. It does not independently check identity or current enrollment.'],
 ['When do I pay?','Arrange payment with the seller at pickup after inspecting the item. PremsCart does not collect money or process refunds.'],
 ['Is an item reserved in my cart?','No. The seller reserves it only when they accept your request. Prices and availability are checked again at checkout.'],
 ['Can I book a rental far in advance?','You can request a preferred pickup date within 90 days, for 1–30 days. This simple project reserves one item at a time after acceptance; it does not offer overlapping calendar reservations. Confirm date availability with the owner.'],
 ['How do I return a rental?','Open Purchases & rentals, select “I’m ready to return it,” and agree on a campus handoff in chat. The owner confirms receiving it back, then both participants can review.'],
 ['What if something goes wrong?','Keep the conversation in chat, open the listing, student review, or message and use Report. Moderators review reports and can hide content or restrict accounts. You can follow your report under Reviews & reports.'],
 ['What is saved on this browser?','Your theme, account-scoped cart, recent searches, recently viewed item IDs, and explicitly saved listing text drafts use browser storage. Images are not saved in text drafts. Sign out on a shared device.'],
 ].map(([q,a])=><details key={q}><summary>{q}<Icon name="plus"/></summary><p>{a}</p></details>)}</section><div className="help-cta"><h2>Ready for your next good find?</h2><a className="button button-primary" href="/marketplace">Explore marketplace<Icon name="arrow"/></a><a className="inline-link" href="/verification">How email verification works</a></div></section>}
