import { BusyLabel } from './Loader'
import { useEffect, useState, type FormEvent } from 'react'
import { api, go } from './api'
import { PrivateImage, FilePreview } from './Media'
import { type Product, priceLabel } from './catalog'
import { EmptyState, ErrorState, Modal, Skeleton, toast } from './UI'
import Icon from './Icon'
type Fields={allowRent:boolean;rentalPrice:string;title:string;description:string;categoryId:string;price:string;transactionType:string;condition:string;location:string;status:string;isNegotiable:boolean}
const blank:Fields={allowRent:false,rentalPrice:'',title:'',description:'',categoryId:'',price:'',transactionType:'Sell',condition:'Good',location:'',status:'Available',isNegotiable:false}
export default function ListingForm({id,token,profile,categories}:{id?:number;token:string;profile:{id:number;role:string}|null;categories:{id:number;categoryName:string}[]}){
 const [form,setForm]=useState<Fields>(blank),[existing,setExisting]=useState<Product|null>(null),[savedId,setSavedId]=useState(id),[photos,setPhotos]=useState<File[]>([]),[loading,setLoading]=useState(!!id),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState(false),[draftExists,setDraftExists]=useState(false),[version,setVersion]=useState(0)
 const key=profile?`premscart-listing-draft-${profile.id}`:''
 useEffect(()=>{if(key&&!id){try{setDraftExists(!!localStorage.getItem(key))}catch{}}},[key,id])
 useEffect(()=>{if(!id)return;let active=true;setLoading(true);api<Product>(`/api/products/${id}`).then(p=>{if(active){setExisting(p);setForm({allowRent:!!p.allowRent,rentalPrice:String(p.rentalPrice??''),title:p.title,description:p.description??'',categoryId:String(p.categoryId),price:String(p.price??''),transactionType:p.transactionType,condition:p.condition??'Good',location:p.location??'',status:p.status,isNegotiable:!!p.isNegotiable})}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[id,version])
 function change<K extends keyof Fields>(key:K,value:Fields[K]){setForm(s=>({...s,[key]:value}))}
 function addPhotos(files:File[]){const max=5-(existing?.images?.length??0);if(photos.length+files.length>max){setError(`You can have five photos total. ${max-photos.length} more can be added.`);return}if(files.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024)){setError('Choose JPEG, PNG, or WebP photos smaller than 5 MB each.');return}setError('');setPhotos(p=>[...p,...files])}
 function saveDraft(){try{localStorage.setItem(key,JSON.stringify(form));setDraftExists(true);toast('Draft saved in this browser. Photos must be selected again.')}catch{setError('Your browser could not save the draft. You can still publish normally.')}}
 function restoreDraft(){try{const saved=JSON.parse(localStorage.getItem(key)??'null');if(saved&&typeof saved.title==='string'){setForm({...blank,...saved});toast('Draft restored. Add your photos when ready.')}}catch{setError('This draft could not be restored. Please start a new listing.')}}
 async function publish(){if(busy)return;setBusy(true);setError('');try{const payload={...form,allowRent:form.transactionType==='Sell'&&form.allowRent,rentalPrice:form.transactionType==='Sell'&&form.allowRent?Number(form.rentalPrice):null,categoryId:Number(form.categoryId),price:form.transactionType==='Giveaway'?0:Number(form.price),isNegotiable:form.transactionType==='Sell'&&form.isNegotiable};const result=await api(savedId?`/api/products/${savedId}`:'/api/products',savedId?'PUT':'POST',payload);const productId=savedId??result.id;setSavedId(productId);const failed:File[]=[];for(const file of photos){const body=new FormData();body.append('file',file);try{await api(`/api/products/${productId}/images`,'POST',body)}catch{failed.push(file)}}setPhotos(failed);if(failed.length){const current=await api<Product>(`/api/products/${productId}`);setExisting(current);setError('Your listing was saved, but some photos did not upload. Retry publishing to upload the remaining photos, or view the saved listing.');setReview(false)}else{if(key&&!id){try{localStorage.removeItem(key)}catch{}}toast(id?'Listing updated.':'Your listing is live.');const wantedId=Number(new URLSearchParams(location.search).get('wantedId'));if(wantedId>0){try{const response=await api(`/api/wanted/${wantedId}/respond`,'POST',{productId});go(`/messages/${response.conversationId}`);return}catch{toast('Listing saved. The wanted post may have closed; you can respond from Wanted later.','error')}}go(`/listings/${productId}`)}}catch(e){setError((e as Error).message);setReview(false)}finally{setBusy(false)}}
 function preview(e:FormEvent){e.preventDefault();setError('');setReview(true)}
 const display={transactionType:form.transactionType,price:form.transactionType==='Giveaway'?0:form.price?Number(form.price):null}
 if(loading)return <Skeleton count={2} label="Loading listing form"/>
 if(profile&&['Admin','Moderator'].includes(profile.role))return <EmptyState title="Use your management workspace." message="Student listing creation is separate from content administration." href={profile.role==='Admin'?'/admin/listings':'/moderator/reports'} label="Open workspace"/>
 if(existing&&profile&&existing.sellerId!==profile.id)return <EmptyState title="This listing belongs to another student." message="Only its owner can edit these details." href="/marketplace" label="Back to marketplace"/>
 if(existing?.isHidden)return <EmptyState title="This listing is hidden by administration." message="Check your notifications for the reason. You can edit it after an administrator restores it." href="/dashboard/notifications" label="View notifications"/>
 const cardPreview=<div className="listing-preview"><div className="listing-preview-photo">{photos[0]?<FilePreview file={photos[0]}/>:<PrivateImage url={existing?.images?.[0]?.imageUrl} token={token} alt={form.title||'Your listing'}/>}<span className={`listing-badge ${form.transactionType.toLowerCase()}`}>{form.transactionType==='Sell'?'For sale':form.transactionType==='Rent'?'For rent':'Giveaway'}</span></div><div><small>{categories.find(c=>String(c.id)===form.categoryId)?.categoryName??'Choose a category'} · {form.condition}</small><h3>{form.title||'Your listing title'}</h3><strong>{form.price||form.transactionType==='Giveaway'?priceLabel(display):'Add your price'}</strong>{form.transactionType==='Sell'&&form.allowRent&&<p>Also for rent · Tk {form.rentalPrice||'—'} / day</p>}<p>{form.location||'Choose campus pickup'}</p></div></div>
 return <section className="page-section listing-editor"><div className="page-heading"><div><span className="eyebrow">GIVE SOMETHING A NEW CHAPTER</span><h1>{id?'Edit your listing':'Post a good find.'}</h1><p>Clear photos and honest details make a great first impression.</p></div><a className="inline-link" href="/dashboard/listings">My listings<Icon name="arrow"/></a></div>{error&&<ErrorState message={error} retry={id&&!existing?()=>setVersion(v=>v+1):undefined}/>}{savedId&&!id&&<p className="admin-notice">Your listing is saved. <a href={`/listings/${savedId}`}>View it here</a>.</p>}{draftExists&&!id&&<div className="draft-notice"><span>You have a saved text draft in this browser.</span><button type="button" onClick={restoreDraft}>Restore draft</button></div>}
 <div className="listing-editor-layout"><form onSubmit={preview} className="structured-listing-form"><fieldset disabled={busy}><legend><span>01</span>Tell us about your item</legend><label>Title<input aria-label="Title" required maxLength={120} placeholder="e.g. Scientific calculator, with cover" value={form.title} onChange={e=>change('title',e.target.value)}/><small>{form.title.length}/120</small></label><div className="form-columns"><label>Category<select required value={form.categoryId} onChange={e=>change('categoryId',e.target.value)}><option value="">Choose category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.categoryName}</option>)}</select></label><label>Condition<select value={form.condition} onChange={e=>change('condition',e.target.value)}>{['New','Like new','Good','Fair'].map(c=><option key={c}>{c}</option>)}</select></label></div><label>Description<textarea aria-label="Description" required minLength={10} maxLength={3000} rows={5} placeholder="What’s included? Mention size, age, any wear, and anything the next owner should know." value={form.description} onChange={e=>change('description',e.target.value)}/><small>{form.description.length}/3000</small></label></fieldset>
 <fieldset disabled={busy}><legend><span>02</span>Choose how to share it</legend><div className="type-picker">{[{type:'Sell',icon:'sale' as const,text:'Find a new owner'},{type:'Rent',icon:'clock' as const,text:'Lend it for a while'},{type:'Giveaway',icon:'gift' as const,text:'Pass it on for free'}].map(t=><label key={t.type} className={form.transactionType===t.type?'selected':''}><input type="radio" name="transactionType" value={t.type} checked={form.transactionType===t.type} onChange={()=>change('transactionType',t.type)}/><Icon name={t.icon}/><strong>{t.type}</strong><small>{t.text}</small></label>)}</div>{form.transactionType!=='Giveaway'?<label>{form.transactionType==='Rent'?'Daily rental price (Tk)':'Asking price (Tk)'}<input type="number" min="0.01" max="9999999999.99" step="0.01" required value={form.price} onChange={e=>change('price',e.target.value)}/></label>:<p className="helper-copy">This listing will be free. You choose who receives it.</p>}{form.transactionType==='Sell'&&<><label className="check-field"><input type="checkbox" checked={form.allowRent} onChange={e=>change('allowRent',e.target.checked)}/>Also offer this item for rent</label>{form.allowRent&&<label>Daily rental price (Tk)<input aria-label="Daily rental price (Tk)" type="number" required min="0.01" max="9999999999.99" step="0.01" value={form.rentalPrice} onChange={e=>change('rentalPrice',e.target.value)}/><small>One item, two choices. Accepting a purchase or rental reserves the same item.</small></label>}</>}
{form.transactionType==='Sell'&&<label className="check-field"><input type="checkbox" checked={form.isNegotiable} onChange={e=>change('isNegotiable',e.target.checked)}/>Open to reasonable offers</label>}{(form.transactionType==='Rent'||form.allowRent)&&<p className="helper-copy">One item per listing. Renters choose preferred dates and 1–30 days. Rental availability is reserved on acceptance until the return is confirmed.</p>}</fieldset>
 <fieldset disabled={busy}><legend><span>03</span>Meet on campus</legend><div className="form-columns"><label>Campus pickup location<select required value={form.location} onChange={e=>change('location',e.target.value)}><option value="">Choose a place</option>{['Main gate','Canteen','Library'].map(l=><option key={l}>{l}</option>)}</select></label><label>Listing visibility<select value={form.status} onChange={e=>change('status',e.target.value)}>{!['Available','Unavailable'].includes(form.status)&&<option value={form.status}>{form.status}</option>}<option value="Available">Available to students</option><option value="Unavailable">Unavailable for now</option></select></label></div><p className="helper-copy">The exact pickup time is agreed with the buyer after you accept.</p></fieldset>
 <fieldset disabled={busy}><legend><span>04</span>Show it off</legend>{existing?.images?.length? <p className="helper-copy">{existing.images.length} photo(s) already saved. <a href={`/listings/${savedId}`}>Manage existing photos</a>.</p>:null}<label className="photo-dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)addPhotos(Array.from(e.dataTransfer.files))}}><Icon name="plus"/><strong>Choose photos or drop them here</strong><span>JPEG, PNG or WebP · up to 5 MB each · five photos total</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{addPhotos(Array.from(e.target.files??[]));e.target.value=''}}/></label>{photos.length>0&&<div className="upload-previews">{photos.map((file,i)=><article key={`${file.name}-${i}`}><FilePreview file={file}/><span>{i===0&&!existing?.images?.length?'Cover photo':`New photo ${i+1}`}</span><div><button type="button" aria-label={`Move ${file.name} earlier`} disabled={i===0} onClick={()=>setPhotos(x=>{const next=[...x];[next[i-1],next[i]]=[next[i],next[i-1]];return next})}>←</button><button type="button" aria-label={`Move ${file.name} later`} disabled={i===photos.length-1} onClick={()=>setPhotos(x=>{const next=[...x];[next[i],next[i+1]]=[next[i+1],next[i]];return next})}>→</button><button type="button" aria-label={`Remove ${file.name}`} onClick={()=>setPhotos(x=>x.filter((_,n)=>n!==i))}><Icon name="close"/></button></div></article>)}</div>}</fieldset><div className="editor-actions">{!id&&<button type="button" className="button button-secondary" disabled={busy||!profile} onClick={saveDraft}>Save text draft</button>}<button className="button button-primary" disabled={busy||!profile}>Preview listing<Icon name="arrow"/></button></div></form><aside className="live-preview"><span className="eyebrow">YOUR LIVE PREVIEW</span>{cardPreview}<p className="helper-copy">Your first new photo is the cover on a new listing. Use the arrows to reorder photos before publishing.</p><div className="listing-tips"><h3>A little care goes a long way.</h3><p>Use clear, well-lit photos. Describe wear honestly. Keep your phone number, address, and student ID out of public listing details.</p></div></aside></div>
 <Modal open={review} title="Ready to share it with campus?" busy={busy} onClose={()=>setReview(false)}>{cardPreview}<p className="preview-description">{form.description}</p><p className="helper-copy">{form.status==='Available'?'Your listing will be visible to signed-in campus members.':'Your listing will stay unavailable until you change its visibility.'}</p><div className="modal-actions"><button disabled={busy} onClick={()=>setReview(false)}>Keep editing</button><button className="button button-primary" disabled={busy} onClick={publish}><BusyLabel busy={busy}>{busy?'Saving your listing…':id?'Save changes':'Publish listing'}</BusyLabel></button></div></Modal>
 </section>
}
