import { useEffect, useState } from 'react'
import { api } from './api'
import { ProductCard, RecentProducts, useWishlist, type Product } from './catalog'
import { EmptyState, ErrorState, Modal, Skeleton, toast, confirmAction } from './UI'
import Icon from './Icon'
import ProductDetail from './ProductDetail'
import ListingForm from './ListingForm'
export { PrivateImage } from './Media'
type Category={id:number;categoryName:string}
type Filters={search:string;categoryId:string;type:string;minPrice:string;maxPrice:string;condition:string;location:string;sort:string;negotiable:string}
const empty:Filters={search:'',categoryId:'',type:'',minPrice:'',maxPrice:'',condition:'',location:'',sort:'newest',negotiable:''}
function initialFilters(path:string):Filters{const q=new URLSearchParams(location.search);return {...empty,...Object.fromEntries(Object.keys(empty).map(k=>[k,q.get(k)??empty[k as keyof Filters]])),...(path==='/rentals'?{type:'Rent'}:path==='/giveaways'?{type:'Giveaway'}:{})}}
export default function Marketplace({token,path}:{token:string;path:string}){
 const detail=/^\/listings\/(\d+)$/.exec(path),editing=/^\/listings\/(\d+)\/edit$/.exec(path),mine=path==='/dashboard/listings'
 const [filters,setFilters]=useState<Filters>(()=>initialFilters(path)),[draft,setDraft]=useState<Filters>(()=>initialFilters(path)),[filterOpen,setFilterOpen]=useState(false)
 const [page,setPage]=useState(()=>Math.max(1,Number(new URLSearchParams(location.search).get('page'))||1)),[version,setVersion]=useState(0)
 const [items,setItems]=useState<Product[]>([]),[total,setTotal]=useState(0),[categories,setCategories]=useState<Category[]>([]),[profile,setProfile]=useState<{id:number;role:string}|null>(null)
 const [error,setError]=useState(''),[filterError,setFilterError]=useState(''),[loading,setLoading]=useState(true),[mineFilter,setMineFilter]=useState('All')
 const wishlist=useWishlist()
 const browse=!detail&&!editing&&path!=='/listings/new'&&!mine,staff=profile?.role==='Admin'||profile?.role==='Moderator'
 useEffect(()=>{let active=true;Promise.all([api<Category[]>('/api/products/categories'),api<{id:number;role:string}>('/api/users/profile')]).then(([c,p])=>{if(active){setCategories(c);setProfile(p)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[])
 useEffect(()=>{if(!browse&&!mine){setLoading(false);return}let active=true;setLoading(true);setError('');const q=new URLSearchParams({page:String(page)});Object.entries(filters).forEach(([k,v])=>{if(v)q.set(k,v)});api(mine?'/api/products/mine':`/api/products?${q}`).then(d=>{if(active){setItems(mine?d:d.items);setTotal(mine?d.length:d.total)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[browse,mine,filters,page,version])
 function commit(next:Filters,newPage=1){setFilters(next);setDraft(next);setPage(newPage);const q=new URLSearchParams();Object.entries(next).forEach(([k,v])=>{if(v&&!(k==='sort'&&v==='newest'))q.set(k,v)});if(newPage>1)q.set('page',String(newPage));history.replaceState({},'',path+(q.size?`?${q}`:''))}
 function apply(){if(draft.minPrice&&draft.maxPrice&&Number(draft.minPrice)>Number(draft.maxPrice)){setFilterError('Minimum price must be less than or equal to maximum price.');return}setFilterError('');commit(draft);setFilterOpen(false)}
 function clear(){commit({...empty,...(path==='/rentals'?{type:'Rent'}:path==='/giveaways'?{type:'Giveaway'}:{})});setFilterError('')}
 const labels:Record<string,string>={search:'Search',categoryId:'Category',type:'Type',minPrice:'Minimum',maxPrice:'Maximum',condition:'Condition',location:'Pickup',negotiable:'Negotiable'}
 const active=Object.entries(filters).filter(([k,v])=>v&&k!=='sort')
 async function remove(p:Product){if(!await confirmAction('Delete this listing?',`“${p.title}” will be removed. Listings with transaction history must be kept.`, 'Delete listing',true))return;try{await api(`/api/products/${p.id}`,'DELETE');toast('Listing deleted.');setVersion(v=>v+1)}catch(e){toast((e as Error).message,'error')}}
 const filterFields=<><label>Category<select value={draft.categoryId} onChange={e=>setDraft(d=>({...d,categoryId:e.target.value}))}><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.categoryName}</option>)}</select></label><label>Listing type<select disabled={path==='/rentals'||path==='/giveaways'} value={draft.type} onChange={e=>setDraft(d=>({...d,type:e.target.value}))}><option value="">All types</option><option value="Sell">For sale</option><option value="Rent">For rent</option><option value="Giveaway">Free items</option></select></label><div className="price-range"><label>Minimum price (Tk)<input type="number" min="0" step="0.01" value={draft.minPrice} onChange={e=>setDraft(d=>({...d,minPrice:e.target.value}))}/></label><label>Maximum price (Tk)<input type="number" min="0" step="0.01" value={draft.maxPrice} onChange={e=>setDraft(d=>({...d,maxPrice:e.target.value}))}/></label></div><p className="helper-copy">Rental filters use the daily rate.</p><label>Condition<select value={draft.condition} onChange={e=>setDraft(d=>({...d,condition:e.target.value}))}><option value="">Any condition</option>{['New','Like new','Good','Fair'].map(x=><option key={x}>{x}</option>)}</select></label><label>Pickup location<select value={draft.location} onChange={e=>setDraft(d=>({...d,location:e.target.value}))}><option value="">All campus locations</option>{['Main gate','Canteen','Library'].map(x=><option key={x}>{x}</option>)}</select></label><label className="check-field"><input type="checkbox" checked={!!draft.negotiable} onChange={e=>setDraft(d=>({...d,negotiable:e.target.checked?'true':''}))}/>Negotiable sales only</label></>
 if(detail)return <ProductDetail id={Number(detail[1])} token={token} profile={profile}/>
 if(editing||path==='/listings/new')return <ListingForm id={editing?Number(editing[1]):undefined} token={token} profile={profile} categories={categories}/>
 const visible=mine?items.filter(p=>mineFilter==='All'||(mineFilter==='Hidden'?p.isHidden:p.status===mineFilter)):items
 return <section className="page-section marketplace-page"><div className="page-heading"><div><span className="eyebrow">{mine?'YOUR SELLING SPACE':'THE CAMPUS MARKETPLACE'}</span><h1>{mine?'Your listings':path==='/rentals'?'Need it for a little while?':path==='/giveaways'?'Good things, given freely.':'Find your next good thing.'}</h1><p>{mine?'Manage your products, rentals, and giveaways in one place.':path==='/rentals'?'Choose your dates, meet the owner, and return it when you’re done.':'Useful things. Familiar faces. Pickup right on campus.'}</p></div>{!staff&&<a className="button button-primary" href="/listings/new"><Icon name="plus"/>Post a listing</a>}</div>
 {browse&&<><nav className="catalog-tabs" aria-label="Browse listing types"><a href="/marketplace" aria-current={path==='/marketplace'&&!filters.type?'page':undefined}>All finds</a><a href="/marketplace?type=Sell" aria-current={filters.type==='Sell'?'page':undefined}>Buy</a><a href="/rentals" aria-current={path==='/rentals'?'page':undefined}>Rent</a><a href="/giveaways" aria-current={path==='/giveaways'?'page':undefined}>Free</a></nav><div className="discovery-toolbar"><form className="discovery-search" onSubmit={e=>{e.preventDefault();commit({...filters,search:draft.search})}}><Icon name="search"/><label className="sr-only" htmlFor="listing-search">Search listings</label><input id="listing-search" value={draft.search} maxLength={100} placeholder="Books, calculators, a new favorite…" onChange={e=>setDraft(d=>({...d,search:e.target.value}))}/><button className="button button-primary" type="submit">Search</button></form><button className="button button-secondary" onClick={()=>{setDraft(filters);setFilterError('');setFilterOpen(true)}}><Icon name="settings"/>Filters{active.length?` (${active.length})`:''}</button><label className="sort-control"><span className="sr-only">Sort listings</span><select aria-label="Sort listings" value={filters.sort} onChange={e=>commit({...filters,sort:e.target.value})}><option value="newest">Newest first</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label></div><div className="filter-chips">{active.map(([k,v])=><button key={k} disabled={k==='type'&&(path==='/rentals'||path==='/giveaways')} onClick={()=>commit({...filters,[k]:''})}>{labels[k]}: {k==='categoryId'?categories.find(c=>String(c.id)===v)?.categoryName??v:k==='negotiable'?'Yes':v}<Icon name="close"/></button>)}{active.length>0&&<button className="text-button" onClick={clear}>Clear filters</button>}</div></>}
 {mine&&<div className="catalog-tabs" role="group" aria-label="Filter my listings">{['All','Available','Reserved','Sold','GivenAway','Unavailable','Hidden'].map(s=><button key={s} aria-pressed={mineFilter===s} className={mineFilter===s?'active':''} onClick={()=>setMineFilter(s)}>{s==='GivenAway'?'Given away':s}</button>)}</div>}
 {error?<ErrorState message={error} retry={()=>setVersion(v=>v+1)}/>:loading?<Skeleton/>:visible.length?<><div className="results-meta"><span>{mine?visible.length:total} listing{total===1?'':'s'}</span>{!mine&&<span>Prices in Bangladeshi taka · Campus pickup</span>}</div><div className="catalog-grid">{visible.map(p=>mine?<div key={p.id} className="owned-listing"><ProductCard product={p} token={token} staff/><span className="status-badge">{p.isHidden?'Hidden by administration':p.status}</span><div className="row-actions"><a className="button button-secondary compact" href={`/listings/${p.id}/edit`}>Edit listing</a><button className="text-button danger-text" onClick={()=>remove(p)}>Delete</button></div></div>:<ProductCard key={p.id} product={p} token={token} saved={wishlist.saved.includes(p.id)} disabled={wishlist.pending.includes(p.id)} onSave={()=>wishlist.toggle(p.id)} staff={staff||p.sellerId===profile?.id}/>)}</div>{!mine&&total>12&&<nav className="pagination" aria-label="Listing pages"><button disabled={page<=1} onClick={()=>{commit(filters,page-1);window.scrollTo(0,0)}}>Previous</button><span>Page {page} of {Math.ceil(total/12)}</span><button disabled={page*12>=total} onClick={()=>{commit(filters,page+1);window.scrollTo(0,0)}}>Next</button></nav>}</>:<EmptyState title={mine?'A little space for your first listing.':'No finds with those filters.'} message={mine?'Have a book, gadget, or something useful to pass on? Give it a second chapter.':'Try a different search, clear the filters, or tell campus what you need in Wanted.'} href={mine?'/listings/new':'/wanted/new'} label={mine?'Post a listing':'Post a wanted request'} action={!mine?clear:undefined} actionLabel="Clear filters" icon={mine?'listing':'search'}/>}
 {browse&&profile&&<RecentProducts userId={profile.id} token={token}/>}
 <Modal open={filterOpen} title="Find your kind of thing" onClose={()=>setFilterOpen(false)}><form className="filter-drawer-form" onSubmit={e=>{e.preventDefault();apply()}}>{filterError&&<p className="form-error" role="alert">{filterError}</p>}{filterFields}<div className="modal-actions"><button type="button" onClick={()=>{setDraft({...empty,...(path==='/rentals'?{type:'Rent'}:path==='/giveaways'?{type:'Giveaway'}:{})});setFilterError('')}}>Reset</button><button className="button button-primary">Show results</button></div></form></Modal>
 </section>
}
