import { useProductRequest } from './RequestState'
import { useEffect, useState } from 'react'
import { api, go } from './api'
import { addToCart } from './cart'
import { PrivateImage } from './Media'
import { type Product, ProductCard, priceLabel, money, purchaseLabel, useWishlist, rememberProduct, RecentProducts } from './catalog'
import { EmptyState, ErrorState, Modal, SafetyNote, Skeleton, toast, confirmAction } from './UI'
import { RentalDates, today } from './rental'
import Icon from './Icon'
export default function ProductDetail({id,token,profile}:{id:number;token:string;profile:{id:number;role:string}|null}){
 const [product,setProduct]=useState<Product|null>(null),[related,setRelated]=useState<Product[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[version,setVersion]=useState(0)
 const [imageIndex,setImageIndex]=useState(0),[expanded,setExpanded]=useState(false),[days,setDays]=useState(1),[start,setStart]=useState(today())
 const [mode,setMode]=useState<string|null>(null)
 const request=useProductRequest(id)
 const wishlist=useWishlist()
 useEffect(()=>{let active=true;setLoading(true);setError('');api<Product>(`/api/products/${id}`).then(p=>{if(active){setProduct(p);setImageIndex(0)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});api<Product[]>(`/api/products/${id}/related`).then(p=>{if(active)setRelated(p)}).catch(()=>{});return()=>{active=false}},[id,version])
 useEffect(()=>{if(product&&profile)rememberProduct(profile.id,product.id)},[product?.id,profile?.id])
 if(loading)return <Skeleton count={2} label="Loading listing details"/>
 if(error)return <><ErrorState message={error} retry={()=>setVersion(v=>v+1)}/><EmptyState title="This listing may no longer be available." message="It might have found a new home or been removed by its owner. Your existing orders are still in Purchases." href="/marketplace" label="Browse other finds"/></>
 if(!product)return null
 const p={...product,transactionType:mode??product.transactionType,price:mode==='Rent'&&product.allowRent?product.rentalPrice??null:product.price},owner=p.sellerId===profile?.id,staff=profile?.role==='Admin'||profile?.role==='Moderator',purchasable=!request&&p.status==='Available'&&!p.isHidden&&!owner&&!staff,images=p.images??[],photo=images[imageIndex]
 async function buy(checkout:boolean){if(!profile)return;try{addToCart(profile.id,{productId:id,mode:p.transactionType,...(p.transactionType==='Rent'?{rentalDays:days,rentalStartDate:start}:{})});if(checkout)go('/cart');else toast('Added to your cart.')}catch(e){toast((e as Error).message,'error')}}
 async function message(){setBusy(true);try{const c=await api<{id:number}>('/api/chat/conversations','POST',{productId:id});go(`/messages/${c.id}`)}catch(e){toast((e as Error).message,'error')}finally{setBusy(false)}}
 async function imageAction(action:'remove'|'primary'){if(!photo)return;if(action==='remove'&&!await confirmAction('Remove this photo?','The other photos and listing details will stay.','Remove photo',true))return;setBusy(true);try{await api(`/api/products/${id}/images/${photo.id}${action==='primary'?'/primary':''}`,action==='primary'?'POST':'DELETE');toast(action==='primary'?'Cover photo updated.':'Photo removed.');setVersion(v=>v+1)}catch(e){toast((e as Error).message,'error')}finally{setBusy(false)}}
 return <article className={`page-section product-page ${purchasable?'has-purchase-bar':''}`}><nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/marketplace">Marketplace</a><Icon name="chevron"/><a href={`/marketplace?categoryId=${p.categoryId??''}`}>{p.categoryName??'Listings'}</a><Icon name="chevron"/><span>{p.title}</span></nav><div className="commerce-detail"><section className="product-gallery" aria-label="Product photos"><button className="gallery-main" disabled={!photo} aria-label={`Expand photo ${imageIndex+1} of ${images.length}`} onClick={()=>setExpanded(true)}><PrivateImage url={photo?.imageUrl} token={token} alt={p.title}/>{images.length>0&&<span>{imageIndex+1} / {images.length} · View larger</span>}</button>{images.length>1&&<div className="gallery-thumbnails" role="group" aria-label="Choose product photo">{images.map((im,i)=><button key={im.id} aria-label={`Photo ${i+1}${im.isPrimary?', cover':''}`} aria-pressed={imageIndex===i} onClick={()=>setImageIndex(i)}><PrivateImage url={im.imageUrl} token={token} alt={`${p.title}, photo ${i+1}`}/></button>)}</div>}{owner&&photo&&!p.isHidden&&<div className="row-actions photo-actions"><button disabled={busy||photo.isPrimary} onClick={()=>imageAction('primary')}>{photo.isPrimary?'Cover photo':'Use as cover'}</button><button disabled={busy} onClick={()=>imageAction('remove')}>Remove this photo</button><a href={`/listings/${id}/edit`}>+ Add photos</a></div>}<section className="product-description"><h2>The details</h2><p>{p.description}</p></section><SafetyNote/></section><section className="product-purchase"><div className="listing-heading"><span className={`listing-badge ${p.transactionType.toLowerCase()}`}>{product.allowRent?'Buy or rent':p.transactionType==='Sell'?'For sale':p.transactionType==='Rent'?'For rent':'Giveaway'}</span><button className="icon-button" aria-label="Copy listing link" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);toast('Listing link copied.')}catch{toast('Copy the link from your browser address bar.')}}}><Icon name="copy"/></button></div><h1>{p.title}</h1><div className="listing-price"><strong>{priceLabel(p)}</strong>{p.isNegotiable&&p.transactionType==='Sell'&&<span>Open to offers</span>}</div><dl className="listing-facts"><div><dt>Condition</dt><dd>{p.condition}</dd></div><div><dt>Pickup</dt><dd>{p.location}</dd></div><div><dt>Availability</dt><dd>{p.isHidden?'Hidden by administration':p.status==='Available'?'Available now':p.status}</dd></div>{p.createdAt&&<div><dt>Posted</dt><dd>{new Date(p.createdAt).toLocaleDateString()}</dd></div>}</dl>
 {product.allowRent&&!owner&&!staff&&!request&&<div className="purchase-mode-picker" role="group" aria-label="Buy or rent this item"><button aria-pressed={p.transactionType==='Sell'} onClick={()=>setMode('Sell')}>Buy · {money(product.price)}</button><button aria-pressed={p.transactionType==='Rent'} onClick={()=>setMode('Rent')}>Rent · {money(product.rentalPrice)} / day</button></div>}
 {p.transactionType==='Rent'&&purchasable&&<div className="rental-selection"><RentalDates start={start} days={days} onChange={(s,d)=>{setStart(s);setDays(d)}}/><p className="rental-total"><span>{days} days × {money(p.price)}</span><strong>{money((p.price??0)*days)}</strong></p></div>}
 {owner?<div className="purchase-buttons"><a className="button button-primary" href={`/listings/${id}/edit`}>Edit your listing</a><a className="button button-secondary" href="/dashboard/sales">View purchase requests</a></div>:staff?<p className="admin-notice">Staff preview. <a href={profile?.role==='Admin'?'/admin/listings':'/moderator/reports'}>Manage this content in your workspace.</a></p>:request?<div className="request-sent-panel"><strong>{request.label}</strong><p>Follow your request, arrange pickup, or cancel it from your order.</p><a className="button button-primary" href={request.href}>View request</a></div>:<><div className="purchase-buttons"><button className="button button-primary" disabled={!purchasable||busy||!profile||(p.transactionType==='Rent'&&!start)} onClick={()=>buy(true)}>{purchaseLabel(p)}<Icon name="arrow"/></button><button className="button button-secondary" disabled={!purchasable||busy||!profile} onClick={()=>buy(false)}><Icon name="purchase"/>Add to cart</button></div><p className="purchase-note">The seller confirms your request. Pay directly at pickup.</p><div className="secondary-purchase-actions">{p.isNegotiable&&p.transactionType==='Sell'&&<button className="text-button" disabled={!purchasable} onClick={()=>window.dispatchEvent(new CustomEvent('premscart-start-transaction',{detail:p}))}><Icon name="offer"/>Make an offer</button>}<button className="text-button" disabled={wishlist.pending.includes(id)} onClick={()=>wishlist.toggle(id)}><Icon name="heart"/>{wishlist.saved.includes(id)?'Saved':'Save for later'}</button></div></>}
 <SellerCard product={p} token={token} onMessage={!owner&&!staff?message:undefined} busy={busy}/>
 {p.storeId&&<a className="store-link" href={`/stores/${p.storeId}`}><Icon name="store"/>More from this student store<Icon name="arrow"/></a>}
 {!owner&&<button className="text-button report-link" onClick={()=>window.dispatchEvent(new CustomEvent('premscart-report',{detail:{productId:id,name:p.title}}))}>Report this listing</button>}
 </section></div>
 {related.length>0&&<section className="related-section"><div className="panel-heading"><div><span className="eyebrow">MORE GOOD FINDS</span><h2>You might also like</h2></div><a className="inline-link" href={`/marketplace?categoryId=${p.categoryId??''}`}>See category<Icon name="arrow"/></a></div><div className="catalog-grid">{related.map(item=><ProductCard key={item.id} product={item} token={token} saved={wishlist.saved.includes(item.id)} onSave={()=>wishlist.toggle(item.id)}/>)}</div></section>}
 {profile&&<RecentProducts userId={profile.id} token={token} exclude={id}/>}
 {purchasable&&<div className="mobile-purchase-bar"><div><small>{p.transactionType==='Rent'?`${days}-day total`:'Your campus find'}</small><strong>{p.transactionType==='Rent'?money((p.price??0)*days):priceLabel(p)}</strong></div><button className="button button-primary" disabled={busy||!profile||(p.transactionType==='Rent'&&!start)} onClick={()=>buy(true)}>{purchaseLabel(p)}<Icon name="arrow"/></button></div>}
 <Modal open={expanded} title={`${p.title} · ${imageIndex+1} / ${images.length}`} onClose={()=>setExpanded(false)}><div className="expanded-photo"><PrivateImage url={photo?.imageUrl} token={token} alt={p.title}/></div>{images.length>1&&<div className="modal-actions"><button disabled={imageIndex===0} onClick={()=>setImageIndex(i=>i-1)}>Previous photo</button><button disabled={imageIndex===images.length-1} onClick={()=>setImageIndex(i=>i+1)}>Next photo</button></div>}</Modal>
 </article>
}
function SellerCard({product:p,token,onMessage,busy}:{product:Product;token:string;onMessage?:()=>void;busy:boolean}){
 const [seller,setSeller]=useState<any>(null),[reputation,setReputation]=useState<any>(null)
 useEffect(()=>{let active=true;if(p.sellerId)Promise.all([api(`/api/users/${p.sellerId}`),api(`/api/community/reputation/${p.sellerId}`)]).then(([s,r])=>{if(active){setSeller(s);setReputation(r)}}).catch(()=>{});return()=>{active=false}},[p.sellerId])
 return <aside className="seller-card"><div className="seller-identity"><div className="seller-avatar">{seller?.profile?.profileImage?<PrivateImage url={seller.profile.profileImage} token={token} alt={p.sellerName??'Seller'}/>:<span>{p.sellerName?.[0]??'P'}</span>}</div><div><a href={`/students/${p.sellerId}`}><strong>{p.sellerName}</strong></a>{(p.sellerVerified||seller?.profile?.isVerified)&&<a href="/verification" className="verified-label" title="This member confirmed access to their university email. Enrollment is not independently checked."><Icon name="shield"/>University email verified</a>}</div></div><div className="seller-reputation"><span><Icon name="star"/>{reputation?.reviewCount>0?`${Number(reputation.averageRating).toFixed(1)} (${reputation.reviewCount} reviews)`:'No reviews yet'}</span>{seller&&<span>{seller.completed} completed exchanges</span>}</div><div className="row-actions"><a className="button button-secondary compact" href={`/students/${p.sellerId}`}>View profile</a>{onMessage&&<button className="button button-secondary compact" disabled={busy||p.status!=='Available'} onClick={onMessage}><Icon name="message"/>Message seller</button>}</div></aside>
}
