import { useEffect, useRef, useState, type ReactNode } from 'react'
import Icon, { type IconName } from './Icon'
export function toast(message:string,kind:'success'|'error'='success'){window.dispatchEvent(new CustomEvent('premscart-toast',{detail:{message,kind}}))}
type Confirmation={title:string;message:string;confirmLabel?:string;danger?:boolean;resolve:(value:boolean)=>void}
export function confirmAction(title:string,message:string,confirmLabel='Confirm',danger=false){return new Promise<boolean>(resolve=>window.dispatchEvent(new CustomEvent('premscart-confirm',{detail:{title,message,confirmLabel,danger,resolve}})))}
export function Modal({open,title,onClose,busy=false,children}:{open:boolean;title:string;onClose:()=>void;busy?:boolean;children:ReactNode}){
 const ref=useRef<HTMLDialogElement>(null)
 useEffect(()=>{if(open&&!ref.current?.open)ref.current?.showModal();else if(!open)ref.current?.close()},[open])
 return <dialog ref={ref} className="ui-dialog" aria-label={title} onCancel={e=>{e.preventDefault();if(!busy)onClose()}}><div className="dialog-heading"><h2>{title}</h2><button type="button" className="icon-button" aria-label="Close dialog" disabled={busy} onClick={onClose}><Icon name="close"/></button></div>{children}</dialog>
}
export function FeedbackHost(){
 const [messages,setMessages]=useState<{id:number;message:string;kind:string}[]>([]),[confirmation,setConfirmation]=useState<Confirmation|null>(null)
 const current=useRef<Confirmation|null>(null),timers=useRef<ReturnType<typeof setTimeout>[]>([])
 useEffect(()=>{let sequence=0;const show=(e:Event)=>{const id=++sequence,detail=(e as CustomEvent).detail;setMessages(x=>[...x.slice(-2),{...detail,id}]);timers.current.push(setTimeout(()=>setMessages(x=>x.filter(m=>m.id!==id)),5500))};const ask=(e:Event)=>{current.current?.resolve(false);current.current=(e as CustomEvent<Confirmation>).detail;setConfirmation(current.current)};window.addEventListener('premscart-toast',show);window.addEventListener('premscart-confirm',ask);return()=>{window.removeEventListener('premscart-toast',show);window.removeEventListener('premscart-confirm',ask);timers.current.forEach(clearTimeout);current.current?.resolve(false)}},[])
 function close(value:boolean){current.current?.resolve(value);current.current=null;setConfirmation(null)}
 return <><div className="toast-stack" aria-live="polite" aria-atomic="false">{messages.map(m=><div key={m.id} className={`toast ${m.kind}`} role="status"><Icon name={m.kind==='error'?'shield':'check'}/><span>{m.message}</span><button className="icon-button" aria-label="Dismiss notification" onClick={()=>setMessages(x=>x.filter(n=>n.id!==m.id))}><Icon name="close"/></button></div>)}</div><Modal open={!!confirmation} title={confirmation?.title??'Confirm action'} onClose={()=>close(false)}><p>{confirmation?.message}</p><div className="modal-actions"><button onClick={()=>close(false)}>Cancel</button><button className={confirmation?.danger?'danger-button':'button button-primary'} onClick={()=>close(true)}>{confirmation?.confirmLabel??'Confirm'}</button></div></Modal></>
}
export function Skeleton({count=4,label='Loading listings'}:{count?:number;label?:string}){return <div role="status" aria-label={label}><span className="sr-only">{label}…</span><div className="skeleton-grid" aria-hidden="true">{Array.from({length:count},(_,i)=><div key={i} className="skeleton-card"><div className="skeleton-media"/><div/><div/><div/></div>)}</div></div>}
export function EmptyState({title,message,href,label,icon='search',action,actionLabel}:{title:string;message:string;href?:string;label?:string;icon?:IconName;action?:()=>void;actionLabel?:string}){return <div className="helpful-empty"><span><Icon name={icon}/></span><h2>{title}</h2><p>{message}</p>{href&&<a className="button button-primary" href={href}>{label}<Icon name="arrow"/></a>}{action&&<button className="button button-secondary" onClick={action}>{actionLabel??label??'Try again'}</button>}</div>}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}){return <div className="error-state" role="alert"><Icon name="shield"/><div><strong>Something needs another try.</strong><p>{message}</p></div>{retry&&<button onClick={retry}>Retry</button>}</div>}
export function SafetyNote(){return <aside className="safety-note"><Icon name="shield"/><div><strong>A good handoff starts with a little care.</strong><p>Meet at Main gate, Canteen, or Library. Inspect the item before paying and keep arrangements in campus chat. <a href="/help">Pickup & safety guide</a></p></div></aside>}
