import { useEffect, useState } from 'react'
import { api, go } from './api'
import { Modal, ErrorState, Skeleton, toast } from './UI'
import { type Product, priceLabel, money } from './catalog'
export default function WantedReply({post,onClose}:{post:{id:number;title:string};onClose:()=>void}){
 const [items,setItems]=useState<Product[]|null>(null),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let live=true;api<Product[]>('/api/products/mine').then(rows=>{if(live)setItems(rows.filter(p=>p.status==='Available'&&!p.isHidden))}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[])
 return <Modal open title={`Respond to “${post.title}”`} onClose={onClose} busy={busy}><p>Send one of your items to this student. They can review it and choose Buy, Rent, or request it as a giveaway. Sending a suggestion does not reserve your item.</p>{error&&<ErrorState message={error}/>} {!items&&!error?<Skeleton count={1} label="Loading your items"/>:items&&<form className="wanted-reply-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await api(`/api/wanted/${post.id}/respond`,'POST',{productId:Number(selected)});toast('Item sent to the student.');go(`/messages/${r.conversationId}`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{items.length?<><label>Your available item<select required aria-label="Your available item" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose an item</option>{items.map(p=><option key={p.id} value={p.id}>{p.title} · {priceLabel(p)}{p.allowRent?` or ${money(p.rentalPrice)}/day`:''}</option>)}</select></label><button className="button button-primary" disabled={busy||!selected}>{busy?'Sending…':'Send item & open chat'}</button></>:<p>You have no available items yet. Post the item you can offer first.</p>}<a className="button button-secondary" href={`/listings/new?wantedId=${post.id}`}>Post an item for this request</a></form>}</Modal>
}
